### ISSUE TITLE
Error on startup with 1.28

### ISSUE THREAD

**Issue by bobbylight** [mgarin/weblaf#157]
My application doesn't start up when using WebLookAndFeel 1.28.  It looks like it's bombing out on a line attempting to work around some issue ("new JSpinner();").  1.27 worked well with my application.

```
C:\PROGRA~2\RText>java -jar RText.jar
UIDefaults.getUI() failed: no ComponentUI class for: javax.swing.JSpinner$Number
Editor[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSiz
e=,minimumSize=,preferredSize=]
java.lang.Error
        at javax.swing.UIDefaults.getUIError(UIDefaults.java:732)
        at javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:130)
        at javax.swing.UIDefaults.getUI(UIDefaults.java:762)
        at javax.swing.UIManager.getUI(UIManager.java:1016)
        at javax.swing.JPanel.updateUI(JPanel.java:126)
        at javax.swing.JPanel.<init>(JPanel.java:86)
        at javax.swing.JPanel.<init>(JPanel.java:95)
        at javax.swing.JSpinner$DefaultEditor.<init>(JSpinner.java:622)
        at javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1209)
        at javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1185)
        at javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1160)
        at javax.swing.JSpinner.createEditor(JSpinner.java:252)
        at javax.swing.JSpinner.<init>(JSpinner.java:158)
        at javax.swing.JSpinner.<init>(JSpinner.java:169)
        at com.alee.laf.WebLookAndFeel$2.propertyChange(WebLookAndFeel.java:865)

        at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)

        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSup
port.java:327)
        at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(Swing
PropertyChangeSupport.java:92)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSup
port.java:263)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:548)
        at org.fife.rtext.RText$2.run(RText.java:1741)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDo
main.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
UIDefaults.getUI() failed: no ComponentUI class for: javax.swing.JFormattedTextF
ield[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=
,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin
=,selectedTextColor=,selectionColor=,columns=0,columnWidth=0,command=,horizontal
Alignment=CENTER]
java.lang.Error
        at javax.swing.UIDefaults.getUIError(UIDefaults.java:732)
        at javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:130)
        at javax.swing.UIDefaults.getUI(UIDefaults.java:762)
        at javax.swing.UIManager.getUI(UIManager.java:1016)
        at javax.swing.text.JTextComponent.updateUI(JTextComponent.java:340)
        at javax.swing.text.JTextComponent.<init>(JTextComponent.java:314)
        at javax.swing.JTextField.<init>(JTextField.java:231)
        at javax.swing.JTextField.<init>(JTextField.java:172)
        at javax.swing.JFormattedTextField.<init>(JFormattedTextField.java:277)
        at javax.swing.JSpinner$DefaultEditor.<init>(JSpinner.java:624)
        at javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1209)
        at javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1185)
        at javax.swing.JSpinner$NumberEditor.<init>(JSpinner.java:1160)
        at javax.swing.JSpinner.createEditor(JSpinner.java:252)
        at javax.swing.JSpinner.<init>(JSpinner.java:158)
        at javax.swing.JSpinner.<init>(JSpinner.java:169)
        at com.alee.laf.WebLookAndFeel$2.propertyChange(WebLookAndFeel.java:865)
```

**Comment by mgarin** [comment]
Unfortunately I weren't able to startup RText due to various issues with image resources.
Also still have never seen this issue anywhere else, so I will postpone this for next update - probably I will be able to find out something about this case.

**Comment by mgarin** [comment]
I have completely removed the part of code which was previously causing this issue in b2d8e24 so it should not appear anymore. I will also be doing some extra changes for L&F-less mode which might also help avoiding some other related exceptions.
