### ISSUE TITLE
NullPointerException while dragging tab in WebDocumentPane

### ISSUE THREAD

**Issue by chaddaniels** [mgarin/weblaf#184]
I encounter a NullPointerException occasionally when dragging tabs around within a WebDocumentPane.  I've narrowed down the cause to multiple drag operations being started during a single drag operation, thus causing the exportDone method in the DocumentDragHandler to be called multiple times.  When it is called multiple times it throws the following exception:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.alee.extended.tab.DocumentDragHandler.exportDone(DocumentDragHandler.java:140)
	at javax.swing.TransferHandler$DragHandler.dragDropEnd(TransferHandler.java:1642)
	at java.awt.dnd.DragSourceContext.dragDropEnd(DragSourceContext.java:435)
	at sun.awt.dnd.SunDragSourceContextPeer$EventDispatcher.run(SunDragSourceContextPeer.java:487)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```
I've created a Pull Request with a change that fixes this issue in my environment.

**Comment by mgarin** [comment]
I guess this one is solved for now.
If something weird pops up again - feel free to reopen this issue.
