### ISSUE TITLE
WebNotification setShadeWidth() Exception and ShadowError

### ISSUE THREAD

**Issue by RobertoDebarba** [mgarin/weblaf#214]
In 1.29, when I call setShadeWidth() in an instantiated object WebNotification occurs a Exception.

```java
lblMensagens.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {
				WebNotification notificationPopup = new WebNotification ();
				notificationPopup.setLayout(new BorderLayout(0, 0));
                notificationPopup.setIcon ( NotificationIcon.mail );
                notificationPopup.setDisplayTime ( 5000 );
                notificationPopup.setShadeWidth(0);
                
                final WebClock clock = new WebClock ();
                clock.setClockType ( ClockType.timer );
                clock.setTimeLeft ( 6000 );
                clock.setTimePattern ( "'This notification will close in' ss 'seconds'" );
                notificationPopup.setContent ( new GroupPanel ( clock ) );

                NotificationManager.showNotification ( notificationPopup );
                clock.start ();
			}
		});
```
```java
java.lang.NoSuchMethodException: com.alee.extended.painter.NinePatchIconPainter.setShadeWidth(java.lang.Integer)
	at com.alee.utils.ReflectUtils.getMethod(ReflectUtils.java:1391)
	at com.alee.utils.ReflectUtils.getMethod(ReflectUtils.java:1387)
	at com.alee.utils.ReflectUtils.getMethod(ReflectUtils.java:1387)
	at com.alee.utils.ReflectUtils.getMethodImpl(ReflectUtils.java:1333)
	at com.alee.utils.ReflectUtils.getMethod(ReflectUtils.java:1300)
	at com.alee.utils.ReflectUtils.callMethod(ReflectUtils.java:1129)
	at com.alee.managers.style.skin.WebLafSkin.setFieldValue(WebLafSkin.java:465)
	at com.alee.managers.style.skin.WebLafSkin.setCustomPainterProperty(WebLafSkin.java:388)
	at com.alee.managers.style.skin.WebLafSkin.setCustomPainterProperty(WebLafSkin.java:369)
	at com.alee.managers.style.StyleManager.setCustomPainterProperty(StyleManager.java:457)
	at com.alee.managers.style.StyleManager.setCustomPainterProperty(StyleManager.java:418)
	at com.alee.laf.panel.WebPanelUI.setShadeWidth(WebPanelUI.java:508)
	at com.alee.laf.panel.WebPanel.setShadeWidth(WebPanel.java:794)
	at openlync.forms.FormIncial$5.mouseClicked(FormIncial.java:175)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6528)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[AWT-EventQueue-0] [ERROR] com.alee.managers.style.skin.WebLafSkin - java.lang.NoSuchFieldException: Field "shadeWidth" not found in class: com.alee.extended.painter.NinePatchIconPainter
java.lang.NoSuchFieldException: Field "shadeWidth" not found in class: com.alee.extended.painter.NinePatchIconPainter
	at com.alee.utils.ReflectUtils.getField(ReflectUtils.java:164)
	at com.alee.managers.style.skin.WebLafSkin.setFieldValue(WebLafSkin.java:484)
	at com.alee.managers.style.skin.WebLafSkin.setCustomPainterProperty(WebLafSkin.java:388)
	at com.alee.managers.style.skin.WebLafSkin.setCustomPainterProperty(WebLafSkin.java:369)
	at com.alee.managers.style.StyleManager.setCustomPainterProperty(StyleManager.java:457)
	at com.alee.managers.style.StyleManager.setCustomPainterProperty(StyleManager.java:418)
	at com.alee.laf.panel.WebPanelUI.setShadeWidth(WebPanelUI.java:508)
	at com.alee.laf.panel.WebPanel.setShadeWidth(WebPanel.java:794)
	at openlync.forms.FormIncial$5.mouseClicked(FormIncial.java:175)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6528)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I use this method because the Shadow Notification is bugged in Ubuntu 14.10 (Unity).
![captura de tela de 2015-01-11 17 30 26](https://cloud.githubusercontent.com/assets/5933968/5696430/53ba8084-99b8-11e4-946b-acf8ce30952f.png)

**Comment by mgarin** [comment]
Thanks for reporting!

This case actually represents two issues:
- Issue with inherited WebPanel methods
- Issue with window transparency on Unix systems

---

Error you have recieved simply indicates that painter installed on the notification panel doesn't support shade option (and other options as well actually since it is image-based). You can setup different painter manually through specifying `NotificationStyle` or `PopupStyle` enumeration into `WebNotification` constructor, for example:
```java
final WebNotification notificationPopup = new WebNotification ( PopupStyle.lightSmall );
```
Those enumeration are made to simplify styling (basically those are some predefined styles for general popups and notifications specifically).

You can also specify painter manually and setup it as you like:
```java
final WebPanelPainter painter = new WebPanelPainter ();
painter.setUndecorated ( false );
painter.setShadeWidth ( 0 );
painter.setRound ( 0 );
final WebNotification notificationPopup = new WebNotification ( painter );
```

This should workaround the exception you have encountered. I will add more predefined styling options which doesn't use shadow with later update so those can be used on Unix systems right away.

That basically solves the first problem.

---

Second problem is hidden deep within the JDK and unfortunately I didn't find any way to workaround it so far (it is already two years old issue). Basically - per-pixel-window-transparency doesn't work on  almost all Unix systems. It works on Windows and Mac OS X though.

It cannot be solved by code so unfortunately I cannot offer any kind of solution to this one. You can only disable custom WebLaF window styling or remove shadows and make all windows/popups square-like so that transparency is not required.

**Comment by RobertoDebarba** [comment]
That's sad =(.
It solved my problem. It's not a good design, but works!

Thanks.

**Comment by mgarin** [comment]
Painters are actually made for any kind of usage, but mostly designed for internal usage so that you would only need to call the component and nothing else. They are still unfinished and will be improved with later releases when everything will be styleable through custom XML themes which will basically specify painters and their settings.
