### ISSUE TITLE
NPE in WebFileChooser

### ISSUE THREAD

**Issue by Sorceror** [mgarin/weblaf#218]
I just got error report from our customer with

```Java
java.lang.NullPointerException
	at com.alee.utils.FileUtils.clearFilesCaches(FileUtils.java:187) ~[weblaf-1.29.2.jar:?]
	at com.alee.laf.filechooser.WebFileChooserPanel.reloadCurrentFolder(WebFileChooserPanel.java:1538) ~[weblaf-1.29.2.jar:?]
	at com.alee.laf.filechooser.WebFileChooserUI.rescanCurrentDirectory(WebFileChooserUI.java:398) ~[weblaf-1.29.2.jar:?]
	at javax.swing.JFileChooser.rescanCurrentDirectory(Unknown Source) ~[?:1.7.0_67]
	at javax.swing.JFileChooser.showDialog(Unknown Source) ~[?:1.7.0_67] 
```

The `reloadCurrentFolder()` method in `WebFileChooserPanel` class lists all files in current folder by method `listFiles()` on `Path` instance. But it may return `null` value as written in documentation in some special cases:

> An array of abstract pathnames denoting the files and directories in the directory denoted by this abstract pathname. The array will be empty if the directory is empty. **Returns null if this abstract pathname does not denote a directory, or if an I/O error occurs**.

I'm not able to tell why there was some I/O occured or what happend exactly, but fix should be quite obvious.

**Comment by mgarin** [comment]
Thanks for pointing out this issue, I will add a fix for this one tomorrow and will upload updated pre-release binaries to the site.

**Comment by Sorceror** [comment]
Thanks, appreciated.
