### ISSUE TITLE
Demo - tooltips - no ComponentUI

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#229]
I'm just running the demo from HEAD. I notice an error in the "Tooltips" tab when hovering over the first line "Swing 750ms delay tooltip". After the delay instead of displaying a tool-tip I get this exception:

```
UIDefaults.getUI() failed: no ComponentUI class for: javax.swing.JToolTip[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=16777224,maximumSize=,minimumSize=,preferredSize=,tipText=]
java.lang.Error
	at javax.swing.UIDefaults.getUIError(UIDefaults.java:732)
	at javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:130)
	at javax.swing.UIDefaults.getUI(UIDefaults.java:762)
	at javax.swing.UIManager.getUI(UIManager.java:1013)
	at javax.swing.JToolTip.updateUI(JToolTip.java:101)
	at javax.swing.JToolTip.<init>(JToolTip.java:83)
	at javax.swing.JComponent.createToolTip(JComponent.java:3065)
	at javax.swing.ToolTipManager.showTipWindow(ToolTipManager.java:286)
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:669)
	at javax.swing.Timer.fireActionPerformed(Timer.java:312)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:244)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
```

This is with OpenJDK 7 on Linux. All other tool-tips in the demo work.

**Comment by Sciss** [comment]
Furthermore, the option-panes tab in the demo doesn't seem to work here:

```
UIDefaults.getUI() failed: no ComponentUI class for: javax.swing.JOptionPane[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,icon=,initialValue=,message=Sample error goes here,messageType=ERROR_MESSAGE,optionType=DEFAULT_OPTION,wantsInput=false]
java.lang.Error
	at javax.swing.UIDefaults.getUIError(UIDefaults.java:732)
	at javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:130)
	at javax.swing.UIDefaults.getUI(UIDefaults.java:762)
	at javax.swing.UIManager.getUI(UIManager.java:1013)
	at javax.swing.JOptionPane.updateUI(JOptionPane.java:1883)
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1846)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:858)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:667)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:638)
	at com.alee.examples.groups.optionpane.ErrorOptionPaneExample$1.actionPerformed(ErrorOptionPaneExample.java:57)
```

Perhaps this is just my sbt-based build (instead of Maven), but since everything else works, I'm wondering.

**Comment by mgarin** [comment]
Unfortunately I don't have a Linux machine available atm so I cannot check whether or not this happens under Linux / OpenJDK 7.

I cannot reproduce this issue under Oracle JDK 6/7/8 on both win & mac machines, but some weird issues appear under OpenJDK from time to time so that might be it. I will be able to check this issue tomorrow and see whether it actually OpenJDK-specific case or not.

**Comment by Sciss** [comment]
Another idea is that it it's directory-of-class-files vs. jar. Because `sbt run` uses the former, it doesn't build jars, so perhaps there is a problem with the way a resource is resolved. I will try to build a fat jar and see if it works in that case.

**Comment by mgarin** [comment]
Just tried both - launching from JAR and from the former project - works in both cases. 
So this is probably something different.

**Comment by mgarin** [comment]
Any news on this one?
I weren't able to reproduce this on Linux (Ubuntu) with OpenJDK 7.
Also seem to work fine under other JDKs and OS.

**Comment by Sciss** [comment]
Ok, it did have to do with the sbt build. By default, sbt doesn't spawn a new JVM when running a project, that can have subtle implications if applications rely on specific class path and resource look-ups. I solved it now in my build, and I guess it never affacted Maven. So closing.

**Comment by mgarin** [comment]
Well, I guess it's fine if unless you will have more issues later on.
