### ISSUE TITLE
java.awt.IllegalComponentStateException

### ISSUE THREAD

**Issue by Sorceror** [mgarin/weblaf#232]
Unfortunately I'm not able to reproduce it on my test machines, but it happen to some our customers few times, here is the stacktrace

```Java
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Unknown Source) ~[?:1.8.0_31]
	at java.awt.Component.getLocationOnScreen(Unknown Source) ~[?:1.8.0_31]
	at com.alee.utils.SwingUtils.getRelativeLocation(SwingUtils.java:2229) ~[weblaf-1.29.3.jar:?]
	at com.alee.utils.SwingUtils.getRelativeBounds(SwingUtils.java:2216) ~[weblaf-1.29.3.jar:?]
	at com.alee.managers.tooltip.WebCustomTooltip.getActualDisplayWay(WebCustomTooltip.java:399) ~[weblaf-1.29.3.jar:?]
	at com.alee.managers.tooltip.WebCustomTooltip.updateBorder(WebCustomTooltip.java:459) ~[weblaf-1.29.3.jar:?]
	at com.alee.managers.tooltip.WebCustomTooltip$2.ancestorMoved(WebCustomTooltip.java:264) ~[weblaf-1.29.3.jar:?]
	at javax.swing.AncestorNotifier.fireAncestorMoved(Unknown Source) ~[?:1.8.0_31]
	at javax.swing.AncestorNotifier.componentMoved(Unknown Source) ~[?:1.8.0_31]
	at java.awt.Component.processComponentEvent(Unknown Source) ~[?:1.8.0_31]
	at java.awt.Component.processEvent(Unknown Source) ~[?:1.8.0_31]
	at java.awt.Container.processEvent(Unknown Source) ~[?:1.8.0_31]
	at java.awt.Component.dispatchEventImpl(Unknown Source) ~[?:1.8.0_31]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[?:1.8.0_31]
	at java.awt.Component.dispatchEvent(Unknown Source) ~[?:1.8.0_31]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_31]
	at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_31]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_31]
	at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_31]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_31]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_31]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_31]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_31]
	at com.project.exceptions.EventQueueExceptionProxy.dispatchEvent(EventQueueExceptionProxy.java:54) [project-1.0.0.jar:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_31]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_31]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_31]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_31]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_31]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_31]
```

Any idea what might cause that problem?

Caught on platform amd64, Windows 8.1 6.3 with Java 1.8.0_31.

**Comment by mgarin** [comment]
It seems that tooltip is trying to update its position, but the component it is attached to is not visible on the screen anymore, though it (that component) or its ancestor has moved for some reason and sent an appropriate Swing event. This is a pretty strange case and its understandable why you aren't able to reproduce it under normal circumstances. 

Probably there was an opened (displayed) tooltip when the component it is attached to became hidden and the window or component's container was moved right afterwards.

I am currently adding a lot of changes and improvements for each manager to fix possible memory leaks (these changes will soon be available) and I will also investigate this case and see what I can do to fix/prevent this issue from happening. Thanks for reporting!

**Comment by mgarin** [comment]
Here are some updates on this case...

I weren't able to reproduce this issue, but I might point out what exactly causes this behavior. 
It is rather simple but it isn't obvious to me why that happens: glass pane where all custom WebLaF tooltips are being displayed is either hidden or removed from the frame. 

This might happen because of:
- 3rd-party library that tries to create its own glass pane to handle some stuff (for example Jide)
- client code which uses glass pane for its own matters
- visibility of glass pane is being altered for some reason

So I can't really say more about this without knowing how does the application your clients write works on the UI side. Though I have added a small workaround for this specific exception and specifically this one shouldn't appear anymore. But I cannot guarantee that all the tooltips will be displayed correctly if something happens with the glass pane.

**Comment by Sorceror** [comment]
Thanks! Narrowing it to glass pane help a lot, we're using that in our GUI, so I know where to look further.

**Comment by mgarin** [comment]
I might be removing glass pane usage later on if that is a real issue. There are other ways to place stuff on top of the UI which won't interfere with other 3rd-party libraries or code and that is already used for some other things within WebLaF.

**Comment by Sorceror** [comment]
Appreciated, but that seems to be race in our code, and because it was reported only by one user so far and was probably caused by his/her obsolete hardware (way far from minimum requirements - slow GUI processing) there is no need right now.

**Comment by mgarin** [comment]
I have edited the post, but removed from there now - guess it was too late :)

Other way is like inner notifications in NotificationManager - those use a separate layer on the frame to position popups. It is basically the same as glass pane, though you can place stuff on any layer you want to.

Layered pane is available within any JRootPane (so basically in JFrame, JDialog and JWindow) and it contains frame content pane and menu bar by default. You are free to add anything you like into it as well. The only limitation is that it is placed under the glass pane and its content could never overlap glasspane content.

For example here is the code that handles popup layers:
```java
    /**
     * Returns cached shade layer for the specified root pane.
     *
     * @param rootPane root pane for the shade layer
     * @return cached shade layer for the specified root pane
     */
    public static ShadeLayer getShadeLayer ( final JRootPane rootPane )
    {
        if ( rootPane == null )
        {
            throw new RuntimeException ( "JRootPane for PopupLayer cannot be found" );
        }
        if ( shadeLayers.containsKey ( rootPane ) )
        {
            return shadeLayers.get ( rootPane );
        }
        else
        {
            final JLayeredPane layeredPane = rootPane.getLayeredPane ();
            if ( layeredPane == null )
            {
                throw new RuntimeException ( "Popup layer can be installed only into window or applet with JLayeredPane" );
            }

            final ShadeLayer shadeLayer = new ShadeLayer ();
            installPopupLayer ( shadeLayer, rootPane, layeredPane );
            shadeLayers.put ( rootPane, shadeLayer );

            return shadeLayer;
        }
    }

    /**
     * Installs popup layer for the specified root pane.
     *
     * @param popupLayer  popup layer to install
     * @param rootPane    root pane for which popup layer should be installed
     * @param layeredPane window's layered pane
     */
    protected static void installPopupLayer ( final PopupLayer popupLayer, final JRootPane rootPane, final JLayeredPane layeredPane )
    {
        popupLayer.setBounds ( 0, 0, layeredPane.getWidth (), layeredPane.getHeight () );
        popupLayer.setVisible ( true );
        layeredPane.add ( popupLayer, JLayeredPane.PALETTE_LAYER );
        layeredPane.revalidate ();

        layeredPane.addComponentListener ( new ComponentAdapter ()
        {
            @Override
            public void componentResized ( final ComponentEvent e )
            {
                popupLayer.setBounds ( 0, 0, layeredPane.getWidth (), layeredPane.getHeight () );
                popupLayer.revalidate ();
            }
        } );

        final Window window = SwingUtils.getWindowAncestor ( rootPane );
        if ( window != null )
        {
            window.addWindowStateListener ( new WindowStateListener ()
            {
                @Override
                public void windowStateChanged ( final WindowEvent e )
                {
                    popupLayer.setBounds ( 0, 0, layeredPane.getWidth (), layeredPane.getHeight () );
                    popupLayer.revalidate ();
                }
            } );
        }
    }
```
Nothing special except the fact you have to keep your layer size "up-to-date" as it won't automatically resize to window's size.

By the way, Swing popups are also placed into JLayeredPane when displayed within the window bounds and are lightweight-enabled. So this isn't really a new feature - it was there since the beginning of Swing :)

**Comment by Sorceror** [comment]
Oh, right. I thought there are different ways than avoids JRootPane completely :).

**Comment by mgarin** [comment]
Well, there is no point in avoiding JRootPane - it is the base of the window.
It contains JLayeredPane (with contentpane and menubar) and glass pane component.

You can use one of those to place your components into or you can simply add something else onto the JRootPane, for example your own container. You just need to setup a custom layout as well in that case, otherwise your component won't be placed properly.

**Comment by Sorceror** [comment]
As I think about it, that might be the problem we're having in our GUI :).

**Comment by mgarin** [comment]
Updated pre-release artifacts are now available here:
http://weblookandfeel.com/downloads/prerelease/
