### ISSUE TITLE
error in initialize L&F in linux

### ISSUE THREAD

**Issue by Abu-Abdullah** [mgarin/weblaf#238]
Hi,

I'm getting this error in linux (with jre 1.8.0_40   64bit)
```
[AWT-EventQueue-0] ERROR com.alee.utils.LafUtils - Unable to initialize L&F for class name: com.alee.laf.WebLookAndFeel
java.lang.ClassNotFoundException: com/alee/laf/WebLookAndFeel
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:1874)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:582)
	at com.alee.utils.LafUtils.setupLookAndFeelSafely(LafUtils.java:1557)
	at com.alee.utils.LafUtils.setupLookAndFeelSafely(LafUtils.java:1544)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:930)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:918)
	at classes.AudioCataloger$58.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

it is working in windows. i tried to set the path manually in the commandline and in the class-path in the jar file.

**Comment by mgarin** [comment]
That sounds pretty simple and weird at the same time.
Could you provide a small example which will throw this on linux system?
I can't check that right now, but I will be able to check it tomorrow.

Are you sure your application has rights to load up classes?
Since this exception basically appears in these methods:
```java
    /**
     * Installs specified L&F as current application's L&F.
     *
     * @param clazz L&F class
     * @return true if L&F was installed successfully, false otherwise
     */
    public static boolean setupLookAndFeelSafely ( final Class<? extends LookAndFeel> clazz )
    {
        return setupLookAndFeelSafely ( clazz.getCanonicalName () );
    }

    /**
     * Installs specified L&F as current application's L&F.
     *
     * @param className L&F canonical class name
     * @return true if L&F was installed successfully, false otherwise
     */
    public static boolean setupLookAndFeelSafely ( final String className )
    {
        try
        {
            UIManager.setLookAndFeel ( className );
            return true;
        }
        catch ( final Throwable e )
        {
            Log.get ().error ( "Unable to initialize L&F for class name: " + className, e );
            return false;
        }
    }
```

**Comment by Abu-Abdullah** [comment]
OK, it seems it is something with env variable: JAVA_TOOL_OPTIONS. the console is showing:
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar

if i set JAVA_TOOL_OPTIONS to nothing, it will start working normally. this is set by default in Ubuntu 15.4
I'm using Oracle JRE and it seems it is mixed with by variable with the default OpenJDK, maybe

now I need to reset this in the launch script. is it the only option, is there anything that can be done. why $JAVA_TOOL_OPTIONS is affecting webLaF

**Comment by mgarin** [comment]
Not sure whether it affects only WebLaF or not.
Could you try running something like this:
```java
    public static void main ( final String[] args )
    {
        try
        {
            UIManager.setLookAndFeel ( NimbusLookAndFeel.class.getCanonicalName () );
        }
        catch ( final Throwable e )
        {
            e.printStackTrace ();
        }
    }
```
Does this specific piece of code works fine?

What if you try to load some other class from 3rd-party library by its name? Like this:
```java
    public static void main ( final String[] args )
    {
        try
        {
            final Class<?> aClass = Class.forName ( "some.class.Name" );
        }
        catch ( final Throwable e )
        {
            e.printStackTrace ();
        }
    }
```
Does that work?

If not - I am afraid the whole reflection thing is not going to work properly and you will have issues somewhere else even if you don't use any L&F.

**Comment by mgarin** [comment]
And about `JAVA_TOOL_OPTIONS` - can't really say anything specific, never seen this stuff.
After googling a bit a have found a few similar discussions and issues like this:
https://bugs.launchpad.net/ubuntu/+source/jayatana/+bug/1427280
It seems that this could actually be some kind of a bug or whatsoever.

**Comment by Abu-Abdullah** [comment]
Nimbus is working fine on the same ubuntu 15.4

i have tested again on Kubuntu 14.10 and it is working just fine. so i guess it is something maybe on ubuntu 15.4 especially it is still beta version so it is too early for this issue.

**Comment by mgarin** [comment]
Thanks for info :)
I'll be in touch if you find out something else about this case.

Also I have checked this on some earlier Ubuntu versions and it works fine.
It seems that might actually be something in that specific version.

**Comment by mgarin** [comment]
Will close this one for now.
