### ISSUE TITLE
Exception (PERPIXEL_TRANSLUCENT translucency is not supported)

### ISSUE THREAD

**Issue by Noltari** [mgarin/weblaf#306]
Release: weblaf v1.28
OS: SunOS 5.10

Exception:
```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.alee.utils.ReflectUtils.callMethod(ReflectUtils.java:1017)
        at com.alee.utils.ProprietaryUtils.setupOpacityBackgroundColor(ProprietaryUtils.java:209)
        at com.alee.utils.ProprietaryUtils.setWindowOpaque(ProprietaryUtils.java:155)
        at com.alee.laf.menu.WebPopupMenuUI$3.propertyChange(WebPopupMenuUI.java:182)
        at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:328)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
        at java.awt.Component.firePropertyChange(Component.java:8422)
        at javax.swing.JPopupMenu.setVisible(JPopupMenu.java:791)
        at javax.swing.JPopupMenu.show(JPopupMenu.java:965)
        at javax.swing.JMenu.setPopupMenuVisible(JMenu.java:345)
        at javax.swing.JPopupMenu.menuSelectionChanged(JPopupMenu.java:1478)
        at javax.swing.MenuSelectionManager.setSelectedPath(MenuSelectionManager.java:125)
        at javax.swing.plaf.basic.BasicMenuUI$Handler.mouseEntered(BasicMenuUI.java:526)
        at java.awt.AWTEventMulticaster.mouseEntered(AWTEventMulticaster.java:299)
        at java.awt.Component.processMouseEvent(Component.java:6534)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6290)
        at java.awt.Container.processEvent(Container.java:2234)
        at java.awt.Component.dispatchEventImpl(Component.java:4881)
        at java.awt.Container.dispatchEventImpl(Container.java:2292)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
        at java.awt.LightweightDispatcher.retargetMouseEnterExit(Container.java:4686)
        at java.awt.LightweightDispatcher.trackMouseEnterExit(Container.java:4665)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4514)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        at java.awt.Container.dispatchEventImpl(Container.java:2278)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.UnsupportedOperationException: PERPIXEL_TRANSLUCENT translucency is not supported
        at java.awt.Window.setBackground(Window.java:3850)
        ... 52 more
```

**Comment by mgarin** [comment]
This issue was certainly appearing in v1.28 but it was fixed with later updates. 
It should not appear anymore on v1.29 pre-release version which can be found here:
http://weblookandfeel.com/downloads/prerelease/

**Comment by mgarin** [comment]
Did the pre-release version help?

**Comment by Noltari** [comment]
Yeah it's fixed now.
Thank you!
