### ISSUE TITLE
HELP ...java.lang.NoClassDefFoundError: Could not initialize class com.alee.managers.style.StyleManager

### ISSUE THREAD

**Issue by Kaly380** [mgarin/weblaf#324]
Please help I'm using weblaf-complete-1.28
The wing add netbeans palette but when attempting to drag an exception sends me a webFileChooserField
![error 1](https://cloud.githubusercontent.com/assets/6775078/8860961/e9519318-314c-11e5-92af-25fd3fe8f5b7.png)
![error 2](https://cloud.githubusercontent.com/assets/6775078/8861018/5a458016-314d-11e5-908c-95b9c3e325a1.png)

Please help

**Comment by mgarin** [comment]
Try v1.29 prerelease version from here:
http://weblookandfeel.com/downloads/prerelease/
It is far more polished and has a lot issue fixes and improvements.

Most probably it will solve this specific issue since `StyleManager` was an experimental feature at the time v1.28 was released and had a list of problems which were resolved with later changes.

**Comment by mgarin** [comment]
Did newer version help?

**Comment by Kaly380** [comment]
Bueno no funciona con la nueva version.
Lo que pasa es que estoy usando mas librerias para mi proyecto lo que pasa para mi parecer es que hay cruce de librerias algo asi no se si estare en lo correcto.

Xq cuando creo un proyecto nuevo y uso solamente la libreria webLookAndFeel funciona bien el problema es cuando uso mas librerias.

Muchas gracias por la ayuda

**Comment by iamchathu** [comment]
Tried with 1.29 pre release when i try to get WebFileDrop to JFrame exception is thrown.

`java
java.lang.RuntimeException: Unable to find LanguageUpdater for component: com.alee.extended.filechooser.WebFileDrop[,0,0,0x0,invalid,layout=com.alee.extended.layout.WrapFlowLayout,alignmentX=0.0,alignmentY=0.0,border=com.alee.utils.laf.WeblafBorder@75a905f4,flags=9,maximumSize=,minimumSize=,preferredSize=]
	at com.alee.managers.language.LanguageManager.getLanguageUpdater(LanguageManager.java:775)
	at com.alee.managers.language.LanguageManager.updateComponent(LanguageManager.java:868)
	at com.alee.managers.language.LanguageManager.registerComponent(LanguageManager.java:543)
	at com.alee.extended.filechooser.WebFileDrop.setLanguage(WebFileDrop.java:610)
	at com.alee.extended.filechooser.WebFileDrop.setShowDefaultDropText(WebFileDrop.java:495)
	at com.alee.extended.filechooser.WebFileDrop.<init>(WebFileDrop.java:92)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:374)
	at org.netbeans.modules.form.CreationFactory.createDefaultInstance(CreationFactory.java:178)
	at org.netbeans.modules.form.RADComponent.createBeanInstance(RADComponent.java:252)
	at org.netbeans.modules.form.RADComponent.initInstance(RADComponent.java:191)
	at org.netbeans.modules.form.MetaComponentCreator.initComponentInstance(MetaComponentCreator.java:1508)
	at org.netbeans.modules.form.MetaComponentCreator.createVisualComponent(MetaComponentCreator.java:975)
	at org.netbeans.modules.form.MetaComponentCreator.access$300(MetaComponentCreator.java:79)
	at org.netbeans.modules.form.MetaComponentCreator$2.run(MetaComponentCreator.java:286)
	at org.netbeans.modules.form.FormLAF$2.run(FormLAF.java:293)
	at org.openide.util.Mutex.doEventAccess(Mutex.java:1368)
	at org.openide.util.Mutex.readAccess(Mutex.java:327)
	at org.netbeans.modules.form.FormLAF.executeWithLookAndFeel(FormLAF.java:276)
	at org.netbeans.modules.form.MetaComponentCreator.precreateVisualComponent(MetaComponentCreator.java:283)
	at org.netbeans.modules.form.MetaComponentCreator.precreateVisualComponent(MetaComponentCreator.java:306)
	at org.netbeans.modules.form.HandleLayer$NewComponentDrag.init(HandleLayer.java:3367)
	at org.netbeans.modules.form.HandleLayer$NewComponentDrag.<init>(HandleLayer.java:3359)
	at org.netbeans.modules.form.HandleLayer.mouseMoved(HandleLayer.java:2167)
	at java.awt.Component.processMouseMotionEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3338)
	at java.awt.Component.processEvent(Component.java:6274)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4505)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
`

**Comment by mgarin** [comment]
As said before in a few other issues - unfortunately WebLaF is not designed to work well without initialization. The issue shown on last stack trace here happens because `LanguageManager` was not initialized and `WebFileDrop` tried to register itself for translational updates.

I might address all UI editor -related issues with the later updates, but unfortunately for now it is not in the top priority list as it requires a descent amount of work and will generally have no effect on the way library works in actual applications outside of the UI editors.

**Comment by Kaly380** [comment]
and what would be the solution that we can apply please......

**Comment by mgarin** [comment]
I am still not sure what is the source of the issue in your case - can you provide specific stack trace with v1.29 pre-release version? Though I am pretty sure that it will have something similar to stacktrace @iamchathu has provided.

The only way to use WebLaF components properly right now - initialize L&F or at least managers beforehand. There is no other way to workaround this.

**Comment by mgarin** [comment]
I will be making some adjustments to the way managers are initialized to allow proper components usage within UI editors like NetBeans one.
