### ISSUE TITLE
NPE in WebLabelUI class

### ISSUE THREAD

**Issue by Sorceror** [mgarin/weblaf#338]
I've just get `NullPointerException` at `WebLabelUI` class with following stack trace

```Java
java.lang.NullPointerException
	at com.alee.laf.label.WebLabelUI.uninstallUI(WebLabelUI.java:119) ~[weblaf-1.29.7.jar:?]
	at javax.swing.JComponent.uninstallUIAndProperties(JComponent.java:681) ~[?:1.8.0_51]
	at javax.swing.JComponent.setUI(JComponent.java:658) ~[?:1.8.0_51]
	at javax.swing.JLabel.setUI(JLabel.java:261) ~[?:1.8.0_51]
	at com.alee.laf.label.WebLabel.updateUI(WebLabel.java:471) ~[weblaf-1.29.7.jar:?]
	at javax.swing.JLabel.<init>(JLabel.java:164) ~[?:1.8.0_51]
	at com.alee.laf.label.WebLabel.<init>(WebLabel.java:227) ~[weblaf-1.29.7.jar:?]
	at com.alee.managers.tooltip.WebCustomTooltip.createDefaultComponent(WebCustomTooltip.java:1207) ~[weblaf-1.29.7.jar:?]
	at com.alee.managers.tooltip.TooltipManager.addTooltip(TooltipManager.java:220) ~[weblaf-1.29.7.jar:?]
	at com.alee.managers.tooltip.TooltipManager.addTooltip(TooltipManager.java:208) ~[weblaf-1.29.7.jar:?]
	at stile.gui.ProjectManagerGUI$ButtonTitleDescriptionGroup.translateInterface(...) ~[?:?]
``` 

My build of WebLaF library (`weblaf-1.29.7.jar`) is based on commit 09367c9c1f0d828ed047e932ca28c5230ad79e99 and does only complete some additional icons.

**Comment by mgarin** [comment]
Looks pretty strange - this NPE can only occur if you try to uninstall UI before even installing it.
But that should never happen in a common flow of things.

What is your JDK / OS version?
Also, could you provide a separate example which I can use to reproduce this issue?

**Comment by Sorceror** [comment]
It was on `Windows 8.1 6.3`, `Java 1.8.0_51 (x64)`, but unfortunately I'm not able to tell you more about that. It happen at one of our customers and I don't have any details for it. It does not happen since then.

**Comment by mgarin** [comment]
I tried pulling out a few different situations with `JLabel` using `WebLabelUI` but it seems to act properly in all cases. It also acts the same with either `master` or `styling` branch version.

I really doubt I will be able to narrow down the source of the issue without any information on the specific usage case of the label there...

**Comment by mgarin** [comment]
While looking once again at the stack trace I actually got a few more ideas to try out.
Will see if it gives any results tomorrow.

**Comment by mgarin** [comment]
Still nothing, there should be something specific causing this issue.
So I'm afraid I won't be able to help unless I have some example causing this.

**Comment by mgarin** [comment]
Moved this to v1.3.0 for now as there is no way to reproduce it so far.

**Comment by mgarin** [comment]
I'll close this issue for now, but if you find any real means to reproduce it - simply reopen it.
So far, unfortunately, I can't help without a specific case.
