### ISSUE TITLE
WebSliderPainter - NullPointerException with focusInsets

### ISSUE THREAD

**Issue by Sciss** [mgarin/weblaf#362]
The exception I'm seeing:

```
java.lang.NullPointerException
	at com.alee.managers.style.skin.web.WebSliderPainter.calculateContentRect(WebSliderPainter.java:307)
	at com.alee.managers.style.skin.web.WebSliderPainter.calculateGeometry(WebSliderPainter.java:282)
	at com.alee.managers.style.skin.web.WebSliderPainter.paint(WebSliderPainter.java:237)
	at com.alee.managers.style.skin.web.WebSliderPainter.paint(WebSliderPainter.java:27)
	at com.alee.laf.slider.WebSliderUI.paint(WebSliderUI.java:165)
```

Apparently, `calculateContentRect` refers to a field `focusInsets` which is never ever initalised (so `null`).

**Comment by mgarin** [comment]
Thanks for the report!
This have been fixed now in `styling` branch.
