### ISSUE TITLE
NPE when updating component UIs after switching to WebLaF

### ISSUE THREAD

**Issue by JFormDesigner** [mgarin/weblaf#376]
When switching a running app from another L&F to WinLaF, I get a NPE in StyleData.updateSkin().
Occurs in the current **styling** branch, but not in master.

Following program demonstrates the issue:
```java
import java.awt.event.*;
import javax.swing.*;
import com.alee.laf.WebLookAndFeel;

public class TestSwitchLaf
{
	public static void main( String[] args ) {
		SwingUtilities.invokeLater( new Runnable() {
			@Override
			public void run() {
				JButton switchLaf = new JButton( "Switch to WebLaF" );
				switchLaf.addActionListener( new ActionListener() {
					@Override
					public void actionPerformed( ActionEvent e ) {
						WebLookAndFeel.install( true );
					}
				} );

				JPanel panel = new JPanel();
				panel.add( new JLabel("hello world") );
				panel.add( switchLaf );

				JOptionPane.showMessageDialog( null, panel );
			}
		} );
	}
}
```
This shows an dialog in the default L&F and clicking the "Switch to WebLaF" button throws following exception:
```
Exception occurred during event dispatching:
java.lang.NullPointerException
	at com.alee.managers.style.StyleData.updateSkin(StyleData.java:311)
	at com.alee.managers.style.StyleData.setStyleId(StyleData.java:377)
	at com.alee.managers.style.StyleManager.setStyleId(StyleManager.java:366)
	at com.alee.managers.style.StyleId.set(StyleId.java:804)
	at com.alee.laf.rootpane.WebRootPaneUI.installUI(WebRootPaneUI.java:147)
	at javax.swing.JComponent.setUI(JComponent.java:670)
	at javax.swing.JRootPane.setUI(JRootPane.java:456)
	at javax.swing.JRootPane.updateUI(JRootPane.java:466)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1209)
	at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1224)
	at javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1200)
	at com.alee.laf.WebLookAndFeel.updateAllComponentUIs(WebLookAndFeel.java:1061)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:939)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:907)
	at TestSwitchLaf$1$1.actionPerformed(TestSwitchLaf.java:20)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1995)
...
```

**Comment by mgarin** [comment]
Looks weird, but I will surely investigate this.
And thanks for the short code example!

**Comment by mgarin** [comment]
This was quite a tricky fix.

The problem itself was obvious - `WebRootPaneUI` sets `StyleId` of its content pane to properly tie it to its own style, but that happens inside of the UI install method which happens before proper UI have been installed into the content pane component. There are also other cases where similar behavior might occur. 

But this whole case is something I want to work properly since it is really useful and quite hard to avoid if you want to structure component styles.

I have added a fix that would push child component UI update before applying its `StyleId` if component doesn't have a proper UI yet. That fixes the problem in case WebLaF is installed as application L&F, otherwise it will throw an appropriate `StyleException` saying that component doesn't have required UI installed.

**Comment by JFormDesigner** [comment]
Many thanks :+1:
