### ISSUE TITLE
JScrollPane setViewport(null)

### ISSUE THREAD

**Issue by RobertBColton** [mgarin/weblaf#384]
Seems to cause an exception with the styling branch using the download from the other issue.
```java
		JScrollPane scroll = new JScrollPane();
		scroll.setViewport(null);
```
```
com.alee.managers.style.StyleException: Component is not specified
	at com.alee.managers.style.StyleManager.checkSupport(StyleManager.java:713)
	at com.alee.managers.style.StyleManager.getData(StyleManager.java:691)
	at com.alee.managers.style.StyleManager.setStyleId(StyleManager.java:360)
	at com.alee.managers.style.StyleId.set(StyleId.java:824)
	at com.alee.laf.scroll.WebScrollPaneUI$1.propertyChange(WebScrollPaneUI.java:115)
	at java.beans.PropertyChangeSupport.fire(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.beans.PropertyChangeSupport.firePropertyChange(Unknown Source)
	at java.awt.Component.firePropertyChange(Unknown Source)
	at javax.swing.JScrollPane.setViewport(Unknown Source)
	at org.lateralgm.main.LGM.main(LGM.java:2092)
```

According to the Java docs, it should be possible to pass null to this method:
https://docs.oracle.com/javase/7/docs/api/javax/swing/JScrollPane.html#setViewport%28javax.swing.JViewport%29

This exception occurs in 1.29 but not in 1.28.

**Comment by mgarin** [comment]
Thanks for pointing this out!
I will add a fix for this issue.

**Comment by mgarin** [comment]
Tried it on the latest version with this code:
```java
public class ScrollPaneExample
{
    public static void main ( final String[] args )
    {
        WebLookAndFeel.install ();

        final JFrame frame = new JFrame ( "Window title" );

        final JScrollPane scrollPane = new JScrollPane ( null );
        frame.add ( scrollPane, BorderLayout.CENTER );

        frame.setSize ( 400, 200 );
        frame.setLocationRelativeTo ( null );
        frame.setVisible ( true );

        scrollPane.setViewportView ( null );
    }
}
```
Both initial and later viewport view are set to `null` and that doesn't cause any exceptions in the code. Looking at the stack trace it might have been an issue fixed a week ago, but hard to say for sure. 

Could you try reproducing this with the latest `styling` snapshots?

**Comment by RobertBColton** [comment]
Actually, setViewport, not setViewportView. I reproduced this in 1.29 on the styling branch.

**Comment by mgarin** [comment]
Indeed, it is just so rarely touched that I automatically went for viewport view :)
I'll check it now.

**Comment by mgarin** [comment]
I have added a small check for this case, it shouldn't be an issue anymore.
Snapshot build with this fix will be available later today.

**Comment by RobertBColton** [comment]
I've tested and can confirm this has been resolved, thanks!
