### ISSUE TITLE
Netbeans LanguageUpdater error when try to place FileField

### ISSUE THREAD

**Issue by Barrow099** [mgarin/weblaf#396]
Error message:
```
java.lang.RuntimeException: Unable to find LanguageUpdater for component: com.alee.laf.button.WebButton[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.5,border=com.alee.utils.laf.WeblafBorder@690954db,flags=16777504,maximumSize=,minimumSize=,preferredSize=,defaultIcon=jar:file:/F:/Programming/API/JAVA/weblaf/weblaf-complete-1.29.jar!/com/alee/laf/filechooser/icons/backward.png,disabledIcon=,disabledSelectedIcon=,margin=null,paintBorder=false,paintFocus=false,pressedIcon=,rolloverEnabled=false,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=,defaultCapable=true]
	at com.alee.managers.language.LanguageManager.getLanguageUpdater(LanguageManager.java:778)
	at com.alee.managers.language.LanguageManager.updateComponent(LanguageManager.java:871)
	at com.alee.managers.language.LanguageManager.registerComponent(LanguageManager.java:540)
	at com.alee.laf.button.WebButton.setLanguage(WebButton.java:989)
	at com.alee.laf.filechooser.WebFileChooserPanel.createNorthContent(WebFileChooserPanel.java:395)
	at com.alee.laf.filechooser.WebFileChooserPanel.<init>(WebFileChooserPanel.java:351)
	at com.alee.laf.filechooser.WebFileChooserUI.installUI(WebFileChooserUI.java:109)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at com.alee.laf.filechooser.WebFileChooser.updateUI(WebFileChooser.java:321)
	at javax.swing.JFileChooser.setup(JFileChooser.java:371)
	at javax.swing.JFileChooser.<init>(JFileChooser.java:352)
	at javax.swing.JFileChooser.<init>(JFileChooser.java:311)
	at com.alee.laf.filechooser.WebFileChooser.<init>(WebFileChooser.java:59)
	at com.alee.extended.filechooser.WebFileChooserField.<init>(WebFileChooserField.java:149)
	at com.alee.extended.filechooser.WebFileChooserField.<init>(WebFileChooserField.java:77)
	at com.alee.extended.filechooser.WebFileChooserField.<init>(WebFileChooserField.java:72)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.netbeans.modules.form.CreationFactory.createDefaultInstance(CreationFactory.java:178)
	at org.netbeans.modules.form.RADComponent.createBeanInstance(RADComponent.java:252)
	at org.netbeans.modules.form.RADComponent.initInstance(RADComponent.java:191)
	at org.netbeans.modules.form.MetaComponentCreator.initComponentInstance(MetaComponentCreator.java:1520)
	at org.netbeans.modules.form.MetaComponentCreator.createVisualComponent(MetaComponentCreator.java:987)
	at org.netbeans.modules.form.MetaComponentCreator.access$300(MetaComponentCreator.java:79)
	at org.netbeans.modules.form.MetaComponentCreator$2.run(MetaComponentCreator.java:282)
	at org.netbeans.modules.form.FormLAF$2.run(FormLAF.java:293)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:138)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:98)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:94)
	at org.openide.util.Mutex.readAccess(Mutex.java:250)
	at org.netbeans.modules.form.FormLAF.executeWithLookAndFeel(FormLAF.java:276)
	at org.netbeans.modules.form.MetaComponentCreator.precreateVisualComponent(MetaComponentCreator.java:279)
	at org.netbeans.modules.form.MetaComponentCreator.precreateVisualComponent(MetaComponentCreator.java:298)
	at org.netbeans.modules.form.HandleLayer$NewComponentDrag.init(HandleLayer.java:3369)
	at org.netbeans.modules.form.HandleLayer$NewComponentDrag.<init>(HandleLayer.java:3361)
	at org.netbeans.modules.form.HandleLayer.mouseMoved(HandleLayer.java:2169)
	at java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:329)
	at java.awt.Component.processMouseMotionEvent(Component.java:6580)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4538)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mgarin** [comment]
Language exception occurs because of the way components are dependant on managers initialization. Pretty much WebLaF managers should be initialized before you create any component, otherwise you will might get a set of exceptions. 

This will be fixed soon along with some other initialization improvements. 

I'll close this issue to keep a single one related to NetBeans: #18
