### ISSUE TITLE
ThreadLocal Infinite Hang

### ISSUE THREAD

**Issue by nickmitchko** [mgarin/weblaf#449]
The library is waiting infinitely to destroy threads. The sample program finishes and then hangs.

Code that causes this issue:
```JAVA
import javax.swing.*;
import java.util.logging.Logger;

/**
 * Created  : nicholai on 3/20/17.
 * Author   : Nicholai Mitchko
 * Package  : PACKAGE_NAME
 * Project  : ChatAggregator
 */
public class SimpleClassTest {
    // Logger
    private static final Logger LOGGER = Logger.getLogger(Aggregator.class.getName());


    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel ( "com.alee.laf.WebLookAndFeel" );
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        JFileChooser excelChooser = new JFileChooser();
        if (excelChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
        }
    }
}
```

```
Full thread dump OpenJDK 64-Bit Server VM (25.121-b13 mixed mode):

"DestroyJavaVM" #24 prio=5 os_prio=0 tid=0x00007f24e000b000 nid=0x3947 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"pool-1-thread-1" #23 prio=5 os_prio=0 tid=0x00007f2464017000 nid=0x397e waiting on condition [0x00007f24788cd000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c601c768> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-2-thread-3" #22 prio=5 os_prio=0 tid=0x00007f24e06a1800 nid=0x397c waiting on condition [0x00007f2478bce000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076d6eee48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-2-thread-2" #21 prio=5 os_prio=0 tid=0x00007f2464004000 nid=0x397b waiting on condition [0x00007f2478ccf000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076d6eee48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"pool-2-thread-1" #20 prio=5 os_prio=0 tid=0x00007f24e0689000 nid=0x397a waiting on condition [0x00007f2478dd0000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076d6eee48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

"TimerQueue" #19 daemon prio=5 os_prio=0 tid=0x00007f24e0610800 nid=0x3978 waiting on condition [0x00007f24792d1000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c5e25098> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.DelayQueue.take(DelayQueue.java:211)
	at javax.swing.TimerQueue.run(TimerQueue.java:174)
	at java.lang.Thread.run(Thread.java:745)

"Image Fetcher 3" #15 daemon prio=8 os_prio=0 tid=0x00007f24e041b000 nid=0x3973 in Object.wait() [0x00007f247a443000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at sun.awt.image.ImageFetcher.nextImage(ImageFetcher.java:147)
	- locked <0x00000006c5e2df70> (a java.util.Vector)
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:200)
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)

"AWT-XAWT" #14 daemon prio=6 os_prio=0 tid=0x00007f24e040f800 nid=0x3972 runnable [0x00007f247a544000]
   java.lang.Thread.State: RUNNABLE
	at sun.awt.X11.XToolkit.waitForEvents(Native Method)
	at sun.awt.X11.XToolkit.run(XToolkit.java:568)
	at sun.awt.X11.XToolkit.run(XToolkit.java:532)
	at java.lang.Thread.run(Thread.java:745)

"Java2D Disposer" #12 daemon prio=10 os_prio=0 tid=0x00007f24e03ee800 nid=0x3971 in Object.wait() [0x00007f24a811f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c5e156f8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c5e156f8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:745)

"Monitor Ctrl-Break" #10 daemon prio=5 os_prio=0 tid=0x00007f24e0271000 nid=0x396e runnable [0x00007f24a8eab000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	- locked <0x000000076e835f48> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	- locked <0x000000076e835f48> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.intellij.rt.execution.application.AppMain$1.run(AppMain.java:84)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x00007f24e00cd000 nid=0x3965 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=0 tid=0x00007f24e00bf800 nid=0x3964 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=0 tid=0x00007f24e00bb000 nid=0x3963 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=0 tid=0x00007f24e00b9800 nid=0x3962 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 tid=0x00007f24e00b6800 nid=0x3961 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 tid=0x00007f24e00b4800 nid=0x3960 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007f24e008d000 nid=0x395e in Object.wait() [0x00007f24a9d8f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c5e2ddc8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
	- locked <0x00000006c5e2ddc8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007f24e0088000 nid=0x395c in Object.wait() [0x00007f24a9e90000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c5e2d4e0> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000006c5e2d4e0> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=0 tid=0x00007f24e0080800 nid=0x395a runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f24e0020000 nid=0x3948 runnable 

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00007f24e0022000 nid=0x394b runnable 

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00007f24e0023800 nid=0x394d runnable 

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00007f24e0025800 nid=0x394f runnable 

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x00007f24e0027000 nid=0x3952 runnable 

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x00007f24e0029000 nid=0x3955 runnable 

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x00007f24e002a800 nid=0x3956 runnable 

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x00007f24e002c800 nid=0x3957 runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007f24e00cf800 nid=0x3966 waiting on condition 

JNI global references: 585

Heap
 PSYoungGen      total 75264K, used 31580K [0x000000076ca00000, 0x0000000771e00000, 0x00000007c0000000)
  eden space 64512K, 48% used [0x000000076ca00000,0x000000076e8d7370,0x0000000770900000)
  from space 10752K, 0% used [0x0000000770900000,0x0000000770900000,0x0000000771380000)
  to   space 10752K, 0% used [0x0000000771380000,0x0000000771380000,0x0000000771e00000)
 ParOldGen       total 121344K, used 8967K [0x00000006c5e00000, 0x00000006cd480000, 0x000000076ca00000)
  object space 121344K, 7% used [0x00000006c5e00000,0x00000006c66c1e90,0x00000006cd480000)
 Metaspace       used 24468K, capacity 24796K, committed 25008K, reserved 1071104K
  class space    used 3276K, capacity 3387K, committed 3504K, reserved 1048576K`

**Comment by mgarin** [comment]
Thanks for reporting the issue!
I will investigate this.

**Comment by mgarin** [comment]
A short question though - which WebLaF version did you use?

**Comment by mgarin** [comment]
I strongly recommend trying out newest version from the `styling` branch as it contains countless bugfixes and improvements. You can find artifacts of this version here:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

**Comment by nickmitchko** [comment]
I was using the master version packaged with all dependencies (the first jar on the readme). I will switch to the other branch.

**Comment by mgarin** [comment]
Did the `styling` branch build fix this issue for you? :)

**Comment by nickmitchko** [comment]
The bug is not present in v1.2.9. Should change the link on master/README.md to v1.2.9

**Comment by mgarin** [comment]
Thanks for the info!

For now `master` branch is frozen until the v1.2.9 update, so I'd rather not change anything there.
I will be updating site links though to point at the newer releases.
