### ISSUE TITLE
Branch "styling" breaks compatibility with other LAFs (Nimbus)

### ISSUE THREAD

**Issue by manticore-projects** [mgarin/weblaf#458]
As recommended I have tried to switch to the "styling" branch, however that breaks simple things like using WebDateField in a Nimbus LAF frame:
```java
SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() {
          try {
            UIManager.setLookAndFeel(NimbusLookAndFeel.class.getName());
          } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
          } 
          
          LanguageManager.setUpdateLocale(false);
          WebLookAndFeel.initializeManagers();
        }
      });
```
The code above works fine with 1.2.9, but when using the "styling" branch I will get exceptions and the frame does not render:
```bash

8438 [AWT-EventQueue-0] ERROR com.alee.laf.scroll.WebScrollPane - java.lang.ClassCastException: javax.swing.plaf.synth.SynthScrollPaneUI cannot be cast to com.alee.laf.scroll.WebScrollPaneUI
java.lang.ClassCastException: javax.swing.plaf.synth.SynthScrollPaneUI cannot be cast to com.alee.laf.scroll.WebScrollPaneUI
	at com.alee.laf.scroll.WebScrollPane.updateUI(WebScrollPane.java:316)
	at javax.swing.JScrollPane.<init>(JScrollPane.java:305)
	at com.alee.laf.scroll.WebScrollPane.<init>(WebScrollPane.java:131)
	at com.alee.laf.scroll.WebScrollPane.<init>(WebScrollPane.java:106)
	at com.alee.laf.scroll.WebScrollPane.<init>(WebScrollPane.java:62)
	at com.manticore.ui.AssessmentPanel$4.run(AssessmentPanel.java:106)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:218)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:133)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:122)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:118)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:110)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Exception in thread "AWT-EventQueue-0" com.alee.managers.style.StyleException: Unable to apply StyleId to 'javax.swing.JViewport[,0,0,0x0,invalid,layout=javax.swing.ViewportLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=25165832,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=false,lastPaintPosition=,scrollUnderway=false]' because it doesn't use WebLaF UI
	at com.alee.managers.style.StyleData.getComponent(StyleData.java:200)
	at com.alee.managers.style.StyleData.setStyleId(StyleData.java:458)
	at com.alee.managers.style.StyleManager.setStyleId(StyleManager.java:479)
	at com.alee.managers.style.StyleId.set(StyleId.java:912)
	at com.alee.laf.scroll.WebScrollPaneUI.installUI(WebScrollPaneUI.java:96)
	at javax.swing.JComponent.setUI(JComponent.java:656)
	at javax.swing.JScrollPane.setUI(JScrollPane.java:380)
	at com.alee.laf.scroll.WebScrollPane.updateUI(WebScrollPane.java:321)
	at javax.swing.JScrollPane.<init>(JScrollPane.java:305)
	at com.alee.laf.scroll.WebScrollPane.<init>(WebScrollPane.java:131)
	at com.alee.laf.scroll.WebScrollPane.<init>(WebScrollPane.java:106)
	at com.alee.laf.scroll.WebScrollPane.<init>(WebScrollPane.java:62)
	at com.manticore.ui.AssessmentPanel$4.run(AssessmentPanel.java:106)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:218)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:133)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:122)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:118)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:110)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by mgarin** [comment]
There is indeed a problem specifically with `WebScrollPane` due to a lot of additional components it contains (different viewports, scroll bars and corner elements). 

I will provide a fix for that along with some other improvements to avoid exceptions being thrown upon component initialization. It will either be ready today or tomorrow as I'm not yet sure how to fix `WebScrollPane` case for L&F-less mode without causing problems for L&F mode.

**Comment by mgarin** [comment]
I found the source of the problem and I will have to add quite a few changes to fix it. I am working on it, but it will take a while, so the fix most probably won't be available before tomorrow's evening.

**Comment by manticore-projects** [comment]
Mikle,

thank you a lot for prompt response and excellent support.
Please take you time, we stick with stable 1.2.9 for now and enforce correct locale en_US, Not a problem at all.

I actually think, back porting LanguageManager.setUpdateLocale ( false ); might be worth a consideration -- but we are
very fine as for now.
Cheers
Andreas

**Comment by mgarin** [comment]
I stopped adding back ports at some point as amount of changes between `master` and `styling` branch is huge - most changes simply have to be fully coded from a scratch instead of being ports from the branch. I'm not saying its the case for this change, but I try to keep things more or less consistent to avoid more issues in the future.

That is unfortunately one of the problems I will have to deal with until the bloated v1.2.9 update is finally released and I can proceed to more frequent and consistent updates.

**Comment by mgarin** [comment]
Just a short update - due to complexity fixes are taking longer than I expected, but they will surely be available soon, so stay tuned for more updates.

**Comment by mgarin** [comment]
I have pushed major changes that I had locally in b2d8e24, there are also some fixes added for this issue, but those do not solve it completely, but only for the scroll pane. I will be doing further adjustments now and will post another update here as soon as those are available.

**Comment by manticore-projects** [comment]
On Tue, 2017-06-20 at 08:22 -0700, Mikle wrote:
> I have pushed major changes that I had locally in b2d8e24, there are also some fixes added for this issue, but those
> do not solve it completely, but only for the scroll pane. I will be doing further adjustments now and will post
> another update here as soon as those are available.
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_ke
> y":"github/mgarin/weblaf","title":"mgarin/weblaf","subtitle":"GitHub repository","main_image_url":"https://cloud.githu
> busercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-
> 9aed-b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/mgarin/weblaf"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mgarin in #458:
> I have pushed major changes that I had locally in b2d8e24, there are also some fixes added for this issue, but those
> do not solve it completely, but only for the scroll pane. I will be doing further adjustments now and will post
> another update here as soon as those are available."}],"action":{"name":"View
> Issue","url":"https://github.com/mgarin/weblaf/issues/458#issuecomment-309794073"}}}

Much appreciated, we will give it a test and return to you on weekend with feedback.
Thanks and cheers

**Comment by mgarin** [comment]
You will most probably still encounter other exceptions as those changes do not solve issue completely, so I'd suggest waiting for the next bunch of changes. I'll be working directly on fixing this specific problem right now so it shouldn't take as long.

**Comment by mgarin** [comment]
Changes are taking more since I had to increase the scope to avoid major reworks of related elements in the future (and to fix a few other semi-related issues). So here is a small update.

So far I've finished working on the most important part of the changes required to make the fix work - new descriptors system for supporting styleable components. Each component implementation that supports styling will now have its own descriptor containing all information related to that component - identifier, class, UI identifier, base and default UI classes etc. Descriptors will also be responsible for performing some common UI-related operations within the component like updating its UI. Descriptors will be managed by `StyleManager` and you will be able to replace existing ones to customize component configuration or even add new ones to provide styling support for your custom components.

Right now I'm working on implementing descriptors usage across all existing components and using data provided by them instead of `StyleableComponent` enumeration in all parts of WebLaF. I'm planning to finish this part by tomorrow's evening and move on to some final tests to ensure everything works properly after these changes are implemented.

**Comment by mgarin** [comment]
I have finished all of the changes and right now I'm fixing some of the issues that appeared. This hopefully won't take long, so I should be able to push all the changes later today. Stay tuned!

**Comment by mgarin** [comment]
This problem should now be fixed, I have pushed last related changes into `styling` branch.
There are also quite a few related changes and fixes coming with this update.

Build is currently running and you will soon be able to get a newer version from maven snapshot repository: https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/
