### ISSUE TITLE
desktoppane needs more than 'Light skin'

### ISSUE THREAD

**Issue by mokun** [mgarin/weblaf#529]
Hi, 

I use a JDesktopPane for an app. 

Sometimes (but not all the time) when I start the app in Eclipse, it complains about the StyleException as follows : 

```
Exception in thread "pool-2-thread-5" com.alee.managers.style.StyleException: Skin 'Light skin' doesn't have any styles for component type: desktoppane[class javax.swing.JDesktopPane, DesktopPaneUI, class com.alee.laf.desktoppane.WebDesktopPaneUI, class com.alee.laf.desktoppane.WebDesktopPaneUI, StyleId [ id: 'desktoppane'; parent: null ]]
	at com.alee.managers.style.data.SkinInfo.getStyle(SkinInfo.java:496)
	at com.alee.managers.style.XmlSkin.getStyle(XmlSkin.java:161)
	at com.alee.managers.style.AbstractSkin.applySkin(AbstractSkin.java:64)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:280)
	at com.alee.managers.style.StyleManager.installSkin(StyleManager.java:1125)
	at com.alee.laf.desktoppane.WebDesktopPaneUI.installUI(WebDesktopPaneUI.java:70)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JDesktopPane.setUI(JDesktopPane.java:169)
	at java.desktop/javax.swing.JDesktopPane.updateUI(JDesktopPane.java:240)
	at org.mars_sim.msp.ui.swing.MainDesktopPane.uiPulse(MainDesktopPane.java:1386)
```

In my MainDesktopPane, I already initializes weblaf with 

```
			WebLookAndFeel.install();
			UIManagers.initialize();

```

However, it's when I call `super.updateUI()` inside an overriding method that it creates this Exception.

```
	@Override
	public void uiPulse(double time) {
		super.updateUI();
		updateWindows();
	}
```

What's the workaround on this ?

Thanks !

**Comment by mgarin** [comment]
This sounds a lot like a usage of Swing component outside of Event Dispatch Thread (EDT).
I think it might be the case mostly because you said:
> ... Sometimes (**but not all the time**) ...

If you aren't familiar with EDT - you can read more about it here: [Event Dispatch Thread](https://github.com/mgarin/weblaf/wiki/Event-Dispatch-Thread)

Generally speaking - any UI-related code **must** be executed on EDT with no exceptions. While Swing does not enforce that and *usually* runs without exceptions - it is not guaranteed and usually causes a lot of random exceptions in larger applications or some unique cases.

I couldn't really reproduce the exception you've shown on a standalone example:
```java
public class DesktopTest
{
    public static void main ( final String[] args )
    {
        SwingUtilities.invokeLater ( new Runnable ()
        {
            @Override
            public void run ()
            {
                try
                {
                    WebLookAndFeel.install ();

                    final JDesktopPane desktopPane = new JDesktopPane ();
                    desktopPane.setPreferredSize ( new Dimension ( 600, 600 ) );

                    final JInternalFrame frame = new JInternalFrame ( "Frame", true, false, true, true );
                    final JButton update = new JButton ( "Sample" );
                    update.addActionListener ( new ActionListener ()
                    {
                        @Override
                        public void actionPerformed ( final ActionEvent e )
                        {
                            desktopPane.updateUI ();
                        }
                    } );
                    frame.add ( update );
                    desktopPane.add ( frame );
                    frame.setClosed ( false );
                    frame.setIcon ( false );
                    frame.setLocation ( 25,25 );
                    frame.pack ();
                    frame.setVisible ( true );

                    TestFrame.show ( desktopPane );
                }
                catch ( final PropertyVetoException ignored )
                {
                    //
                }
            }
        } );
    }
}
```

What I would suggest first - try enabling this option:
```java
WebLookAndFeel.setForceSingleEventsThread ( true );
```
Right at the start of your application, before you install L&F or create any UI elements. If you have any Swing code running outside of EDT - it will throw exceptions and halt further execution of the Swing-related code.

If you want to simply receive exceptions but allow UI to continue running - you can also setup a different handler for those exceptions, for instance this one:
```java
WebLookAndFeel.setNonEventThreadHandler ( new NonEventThreadHandler ()
{
    @Override
    public void handle ( final RuntimeException e )
    {
        LoggerFactory.getLogger ( DesktopTest.class ).error ( e.getMessage (), e );
    }
} );
```
You can also read more about this option here: [Forced EDT usage](https://github.com/mgarin/weblaf/wiki/Forced-EDT-usage)

Once it's set - try running your application, if there is anything wrong with UI code usage - you would usually get a handful of exceptions pointing at exact locations of the non-EDT calls that must be invoked within EDT.

If you have everything running smooth and without any exceptions thrown - then the exception might have something to do with your application code in particular. Some tricky component use case or some additional code that interferes with component or it's UI logic. Or maybe a faulty style. There could be quite a few issues and I can't really tell what it is exactly without a standalone example that would reproduce the issue.

**Comment by mgarin** [comment]
Just a side not about EDT - it's usage necessity is not dictated by WebLaF, but by Swing overall. 
You can check the official Oracle guide about it here:
https://docs.oracle.com/javase/tutorial/uiswing/concurrency/dispatch.html

**Comment by mgarin** [comment]
Glad that helped :)

Swing can be unpredictable when used outside of EDT, so I do strongly recommend following the practice of running all UI-related code in EDT - that should save you a lot of time in the future.
