### ISSUE TITLE
Issue with JScrollPane's updateUI call

### ISSUE THREAD

**Issue by mgarin** [mgarin/weblaf#563]
@Sciss mentioned on Gitter:

> I'm running into this:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at javax.swing.ScrollPaneLayout.addSingletonComponent(ScrollPaneLayout.java:202)
    at javax.swing.ScrollPaneLayout.addLayoutComponent(ScrollPaneLayout.java:254)
    at java.awt.Container.addImpl(Container.java:1132)
    at java.awt.Container.add(Container.java:975)
    at javax.swing.JScrollPane.setCorner(JScrollPane.java:1267)
    at com.alee.laf.scroll.WebScrollPaneUI.updateCorners(WebScrollPaneUI.java:575)
    at com.alee.laf.scroll.WebScrollPaneUI.installUI(WebScrollPaneUI.java:94)
    at javax.swing.JComponent.setUI(JComponent.java:666)
    at javax.swing.JScrollPane.setUI(JScrollPane.java:380)
    at javax.swing.JScrollPane.updateUI(JScrollPane.java:393)
    at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1238)
    at javax.swing.SwingUtilities.updateComponentTreeUI0(SwingUtilities.java:1253)
    at javax.swing.SwingUtilities.updateComponentTreeUI(SwingUtilities.java:1229)
    at bibliothek.gui.dock.themes.BasicTheme.updateUI(BasicTheme.java:222)
    at bibliothek.gui.dock.themes.BasicTheme.install(BasicTheme.java:187)
    at bibliothek.gui.dock.themes.BasicTheme.install(BasicTheme.java:170)
    at bibliothek.gui.dock.themes.ThemeManager.setTheme(ThemeManager.java:278)
    at bibliothek.gui.DockController.setTheme(DockController.java:788)
    at bibliothek.gui.DockController.initiate(DockController.java:391)
    at bibliothek.gui.DockController.<init>(DockController.java:275)
    at bibliothek.gui.DockController.<init>(DockController.java:260)
    at bibliothek.gui.dock.common.intern.CDockController.<init>(CDockController.java:47)
    at bibliothek.gui.dock.common.intern.EfficientControlFactory.createController(EfficientControlFactory.java:49)
    at bibliothek.gui.dock.common.CControl.init(CControl.java:497)
    at bibliothek.gui.dock.common.CControl.<init>(CControl.java:475)
    at bibliothek.gui.dock.common.CControl.<init>(CControl.java:459)
    at bibliothek.gui.dock.common.CControl.<init>(CControl.java:404)
    at bibliothek.gui.dock.common.CControl.<init>(CControl.java:381)
    at de.sciss.synth.swing.Main$.dockCtrl$lzycompute(Main.scala:195)
```
> Seems that the caching of scroll pane corners is buggy, because their parents might be `null` (after previous removal) and this is not handled by `ScrollPaneLayout`

> it's that the docking framework (https://github.com/Benoker/DockingFrames) calls `updateComponentTreeUI` because it has it's own skinning system. So this after WebLaF has been initialized.

> a workaround might be to install a sub-class of ScrollPaneLayout that handles the case where `oldC.getParent == null`

**Comment by Sciss** [comment]
Here my temporary work-around: https://github.com/Sciss/Submin/blob/b404264e83ba206daa3d1ac011b939797cde23f1/src/main/java/de/sciss/submin/SubminScrollPaneUI.java#L12

**Comment by mgarin** [comment]
I've fixed this NPE along with a few internal issues that weren't really affecting anything visually.
