### ISSUE TITLE
Error when trying to use custom component

### ISSUE THREAD

**Issue by mvrozanti** [mgarin/weblaf#564]
Hi there

I've just added a [new dependency](https://github.com/Qualtagh/JBroTable) to my project to have a JTable with merged column headers and I got a ton of errors after doing so: http://ix.io/1YED, also leaving me without WebUI headers nor the "normal" headers, just a gray background:

![image](https://user-images.githubusercontent.com/11381662/66776931-fb020300-ee9d-11e9-92d4-6cb479190b80.png)

After reading #110 I kind of get why it's happening. But I don't understand how to do the ignore component thing. It would be even nicer if I didn't have to add XMLs to my project. What can I do to have the JBroTable coexist with WebLAF?

**Comment by mgarin** [comment]
According to the stack trace you provided, this part in particular:
```
java.lang.NoSuchFieldException: Field "painter" not found in class: io.github.qualtagh.swing.table.view.JBroTableHeaderUI
	at com.alee.utils.ReflectUtils.getField(ReflectUtils.java:233)
	at com.alee.managers.style.data.ComponentStyle.setFieldValue(ComponentStyle.java:538)
	at com.alee.managers.style.data.ComponentStyle.installPainter(ComponentStyle.java:415)
	at com.alee.managers.style.data.ComponentStyle.apply(ComponentStyle.java:350)
	at com.alee.managers.style.AbstractSkin.applySkin(AbstractSkin.java:65)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:250)
	at com.alee.managers.style.StyleManager.installSkin(StyleManager.java:369)
	at com.alee.laf.table.WebTableHeaderUI.installUI(WebTableHeaderUI.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.github.qualtagh.swing.table.view.JBroTableHeaderUI.call(JBroTableHeaderUI.java:185)
	at io.github.qualtagh.swing.table.view.JBroTableHeaderUI.call(JBroTableHeaderUI.java:174)
	at io.github.qualtagh.swing.table.view.JBroTableHeaderUI.updateModel(JBroTableHeaderUI.java:283)
	at io.github.qualtagh.swing.table.view.JBroTableHeaderUI.installUI(JBroTableHeaderUI.java:316)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.table.JTableHeader.setUI(JTableHeader.java:461)
	at io.github.qualtagh.swing.table.view.JBroTableHeader.<init>(JBroTableHeader.java:87)
	at io.github.qualtagh.swing.table.view.JBroTable.createDefaultTableHeader(JBroTable.java:470)
	at javax.swing.JTable.initializeLocalVars(JTable.java:5529)
	at javax.swing.JTable.<init>(JTable.java:637)
	at javax.swing.JTable.<init>(JTable.java:576)
	at io.github.qualtagh.swing.table.view.JBroTable.<init>(JBroTable.java:59)
	at s4desk.operacao.view.JPanelFloorPlanMae.<init>(JPanelFloorPlanMae.java:69)
	at s4desk.operacao.view.JPanelFloorPlanMae.main(JPanelFloorPlanMae.java:438)
```
`JBroTableHeaderUI` does something really sketchy and it's not surprising it doesn't work. 

According to the source code:

https://github.com/Qualtagh/JBroTable/blob/master/src/io/github/qualtagh/swing/table/view/JBroTableHeaderUI.java#L169-L197

`JBroTableHeaderUI` tries to be a middleman between the actual UI implementation of the current L&F and the table which doesn't really work well with WebLaF for a number of reasons.

I did a bit of research and unfortunately there is no easy fix that I can do on WebLaF side to workaround that problem without having hard dependencies on `JBroTable` library. And even with hard dependency it would be quite a hack. 

> After reading #110 I kind of get why it's happening. But I don't understand how to do the ignore component thing. 

This happens because `tableheader` style declaration has a painter:
```xml
    <!-- Table header -->
    <style type="tableheader">
        <component>
            <opaque>true</opaque>
            <foreground>black</foreground>
        </component>
        <painter>
            <headerHeight>22</headerHeight>
            <topBgColor>226,226,226</topBgColor>
            <bottomBgColor>201,201,201</bottomBgColor>
            <gridColor>170,170,170</gridColor>
        </painter>

        <!-- Default table header cell renderer label -->
        <style type="label" id="renderer" extends="shadow" padding="0,2,1,2">
            <component>
                <opaque>true</opaque>
                <horizontalAlignment>0</horizontalAlignment>
            </component>
        </style>

    </style>
```
And when `StyleManager` tries to apply this default style to your table header UI it retrieves `JBroTableHeaderUI` there instead of `WebTableHeaderUI`. And `JBroTableHeaderUI` obviously doesn't have a `painter` field, therefore you get the `java.lang.NoSuchFieldException` from Reflection.

> It would be even nicer if I didn't have to add XMLs to my project. What can I do to have the JBroTable coexist with WebLAF?

Normally you wouldn't need to touch XML and do any custom styling if you just want to use WebLaF "as is" for a common Swing app, but the problem in this particular case is that you want to use a custom component that injects itself between L&F UI implementation and the component which can certainly cause unpredictable behavior depending on installed L&F (and does in case with WebLaF). This on its own is quite far from a common use case :)

---

Right now I can't really think of a good solution as there are even a few style limitations in place that wouldn't allow making a workaround for this problem.

I might look into allowing complete style overwrite and then there will be a way to fix the issue with `JBroTableHeaderUI`.

**Comment by mvrozanti** [comment]
From what I understand, that seems more of a bug on JBroTable's part for not supporting custom LAFs. Thank you for the complete answer anyways!

**Comment by mgarin** [comment]
To be fair to `JBroTable` project - it's not that simple. I can certainly say that it would work with some custom L&Fs I know, but then won't with others, including WebLaF.

With WebLaF in particular it's even more complicated because of the overall L&F implementation of the styling and other aspects.
