### ISSUE TITLE
Weird exception

### ISSUE THREAD

**Issue by stefan-reich** [mgarin/weblaf#565]
Hi,

I get this exception when trying to install WebLAF. I'm using an older version of WebLAF, so I should probably upgrade and try again. Also, I roll my own class loaders, so the issue could be in there. Any ideas?

```
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at main.swingAndWait(m1024932.java:8240)
	at main.swingAndWait(m1024932.java:8248)
	at main.swing(m1024932.java:4202)
	at main.installWebLAF(m1024932.java:7060)
	at main.setLookAndFeel(m1024932.java:1926)
	at main.main(m1024932.java:319)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at x30.invokeMethod(x30.java:9075)
	at x30.callOpt_withVarargs(x30.java:14584)
	at x30.callOpt(x30.java:9581)
	at x30.callMain(x30.java:5687)
	at x30.runMainMethod(x30.java:1258)
	at x30.paaRun(x30.java:1234)
	at x30.runProgramQuick(x30.java:1225)
	at x30.runProgram(x30.java:1176)
	at x30.javax2(x30.java:989)
	at x30.javaxmain(x30.java:397)
	at x30.goMain(x30.java:329)
	at x30.main(x30.java:161)
Caused by: java.lang.RuntimeException: Unable to initialize LaF for class name: com.alee.laf.WebLookAndFeel
	at com.alee.utils.LafUtils.setupLookAndFeel(LafUtils.java:228)
	at com.alee.utils.LafUtils.setupLookAndFeel(LafUtils.java:211)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:933)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:912)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:900)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at main.invokeMethod(m1024932.java:8386)
	at main.call_withVarargs(m1024932.java:10024)
	at main.call(m1024932.java:3943)
	at main$151.run(m1024932.java:7062)
	at main.callF(m1024932.java:2477)
	at main$168.run(m1024932.java:8249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.alee.api.clone.CloneException: Unable to clone object field: private com.alee.managers.style.data.PainterStyle com.alee.managers.style.data.ComponentStyle.painterStyle
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:133)
	at com.alee.api.clone.Clone$InternalClone.cloneFields(Clone.java:181)
	at com.alee.managers.style.data.ComponentStyle.clone(ComponentStyle.java:865)
	at com.alee.managers.style.data.ComponentStyle.clone(ComponentStyle.java:54)
	at com.alee.api.clone.behavior.CloneableCloneBehavior.clone(CloneableCloneBehavior.java:66)
	at com.alee.api.clone.behavior.CloneableCloneBehavior.clone(CloneableCloneBehavior.java:32)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:130)
	at com.alee.api.clone.Clone.clone(Clone.java:102)
	at com.alee.managers.style.data.ComponentStyle.clone(ComponentStyle.java:886)
	at com.alee.managers.style.data.SkinInfo.performOverride(SkinInfo.java:728)
	at com.alee.managers.style.data.SkinInfo.performOverride(SkinInfo.java:644)
	at com.alee.managers.style.data.SkinInfo.ensureCacheInitialized(SkinInfo.java:513)
	at com.alee.managers.style.data.SkinInfo.getStyle(SkinInfo.java:457)
	at com.alee.managers.style.XmlSkin.getStyle(XmlSkin.java:159)
	at com.alee.managers.style.AbstractSkin.applySkin(AbstractSkin.java:64)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:280)
	at com.alee.managers.style.StyleManager.installSkin(StyleManager.java:1055)
	at com.alee.laf.label.WebLabelUI.installUI(WebLabelUI.java:62)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JLabel.setUI(JLabel.java:256)
	at java.desktop/javax.swing.JLabel.updateUI(JLabel.java:270)
	at java.desktop/javax.swing.border.TitledBorder.lambda$installPropertyChangeListeners$0(TitledBorder.java:768)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:596)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:633)
	at com.alee.utils.LafUtils.setupLookAndFeel(LafUtils.java:224)
	... 27 more
Caused by: com.alee.api.clone.CloneException: Unable to clone object field: private java.util.LinkedHashMap com.alee.managers.style.data.PainterStyle.properties
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:133)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:130)
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:125)
	... 55 more
Caused by: com.alee.api.clone.CloneException: Unable to clone map: {decorations=com.alee.painter.decoration.Decorations@6d1cc93f}
	at com.alee.api.clone.behavior.MapCloneBehavior.clone(MapCloneBehavior.java:135)
	at com.alee.api.clone.behavior.MapCloneBehavior.clone(MapCloneBehavior.java:37)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:130)
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:125)
	... 57 more
Caused by: com.alee.api.clone.CloneException: Unable to clone object field: private java.util.List com.alee.painter.decoration.Decorations.decorations
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:133)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:130)
	at com.alee.api.clone.behavior.MapCloneBehavior.clone(MapCloneBehavior.java:114)
	... 60 more
Caused by: com.alee.api.clone.CloneException: Unable to clone collection: [WebDecoration [ id=default; visible=true ]]
	at com.alee.api.clone.behavior.CollectionCloneBehavior.clone(CollectionCloneBehavior.java:119)
	at com.alee.api.clone.behavior.CollectionCloneBehavior.clone(CollectionCloneBehavior.java:40)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:130)
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:125)
	... 62 more
Caused by: com.alee.api.clone.CloneException: Unable to clone object field: protected java.util.List com.alee.painter.decoration.WebDecoration.shapes
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:133)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:130)
	at com.alee.api.clone.behavior.CollectionCloneBehavior.clone(CollectionCloneBehavior.java:94)
	... 65 more
Caused by: com.alee.api.clone.CloneException: Unable to clone collection: [com.alee.painter.decoration.shape.WebShape@4282b519]
	at com.alee.api.clone.behavior.CollectionCloneBehavior.clone(CollectionCloneBehavior.java:119)
	at com.alee.api.clone.behavior.CollectionCloneBehavior.clone(CollectionCloneBehavior.java:40)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:130)
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:125)
	... 67 more
Caused by: com.alee.api.clone.CloneException: Unable to clone object field: protected com.alee.painter.decoration.shape.Round com.alee.painter.decoration.shape.WebShape.round
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:133)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:130)
	at com.alee.api.clone.behavior.CollectionCloneBehavior.clone(CollectionCloneBehavior.java:94)
	... 70 more
Caused by: com.alee.api.clone.CloneException: Unable to clone object field: public final int com.alee.painter.decoration.shape.Round.topLeft
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:133)
	at com.alee.api.clone.Clone$InternalClone.clone(Clone.java:130)
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:125)
	... 72 more
Caused by: com.alee.utils.reflection.ReflectionException: Unable to update field modifiers: public final int com.alee.painter.decoration.shape.Round.topLeft -> 1
	at com.alee.utils.ReflectUtils.setFieldModifiers(ReflectUtils.java:972)
	at com.alee.utils.ReflectUtils.setFieldValue(ReflectUtils.java:942)
	at com.alee.api.clone.behavior.ReflectionCloneBehavior.clone(ReflectionCloneBehavior.java:128)
	... 74 more
FAIL: java.lang.reflect.InvocationTargetException

Error: ReflectionException: Unable to update field modifiers: public final int com.alee.painter.decoration.shape.Round.topLeft -> 1
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at main.swingAndWait(m1024932.java:8240)
	at main.swingAndWait(m1024932.java:8248)
	at main.infoMessage_noprint(m1024932.java:8937)
	at main.infoMessage(m1024932.java:8925)
	at main.infoMessage(m1024932.java:8920)
	at main.infoBox(m1024932.java:2841)
	at main$8.get(m1024932.java:190)
	at main$8.get(m1024932.java:1)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at main.invokeMethod(m1024932.java:8386)
	at main.callF(m1024932.java:2499)
	at main._handleException(m1024932.java:3201)
	at main.main(m1024932.java:319)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at x30.invokeMethod(x30.java:9075)
	at x30.callOpt_withVarargs(x30.java:14584)
	at x30.callOpt(x30.java:9581)
	at x30.callMain(x30.java:5687)
	at x30.runMainMethod(x30.java:1258)
	at x30.paaRun(x30.java:1234)
	at x30.runProgramQuick(x30.java:1225)
	at x30.runProgram(x30.java:1176)
	at x30.javax2(x30.java:989)
	at x30.javaxmain(x30.java:397)
	at x30.goMain(x30.java:329)
	at x30.main(x30.java:161)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at main.rethrow(m1024932.java:2335)
	at main.nuObject(m1024932.java:11806)
	at main$280.get(m1024932.java:15428)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at main.invokeMethod(m1024932.java:8386)
	at main.callF(m1024932.java:2495)
	at main.swingAndWait(m1024932.java:8245)
	at main.swing(m1024932.java:4206)
	at main.swingConstruct(m1024932.java:15428)
	at main.swingNu(m1024932.java:8598)
	at main.jTextAreaWithUndo(m1024932.java:22682)
	at main.jTextArea(m1024932.java:20798)
	at main.jTextArea(m1024932.java:20794)
	at main.jtextarea(m1024932.java:22412)
	at main.wrappedTextArea(m1024932.java:20112)
	at main.wrappedTextArea(m1024932.java:20116)
	at main.infoMessage_makePanel(m1024932.java:15543)
	at main$173.get(m1024932.java:8938)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at main.invokeMethod(m1024932.java:8386)
	at main.callF(m1024932.java:2495)
	at main$168.run(m1024932.java:8249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at main.nuObject(m1024932.java:11805)
	... 39 more
Caused by: com.alee.managers.style.StyleException: Skin 'Light skin' doesn't have any styles for component type: textarea[class javax.swing.JTextArea, TextAreaUI, class com.alee.laf.text.WTextAreaUI, class com.alee.laf.text.WebTextAreaUI, StyleId [ id: 'textarea'; parent: null ]]
	at com.alee.managers.style.data.SkinInfo.getStyle(SkinInfo.java:496)
	at com.alee.managers.style.XmlSkin.getStyle(XmlSkin.java:159)
	at com.alee.managers.style.AbstractSkin.applySkin(AbstractSkin.java:64)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:280)
	at com.alee.managers.style.StyleManager.installSkin(StyleManager.java:1055)
	at com.alee.laf.text.WebTextAreaUI.installUI(WebTextAreaUI.java:78)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.text.JTextComponent.setUI(JTextComponent.java:342)
	at java.desktop/javax.swing.text.JTextComponent.updateUI(JTextComponent.java:352)
	at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:326)
	at java.desktop/javax.swing.JTextArea.<init>(JTextArea.java:199)
	at java.desktop/javax.swing.JTextArea.<init>(JTextArea.java:145)
	... 45 more
FAIL: java.lang.reflect.InvocationTargetException

java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at main.swingAndWait(m1024932.java:8240)
	at main.swingAndWait(m1024932.java:8248)
	at main.swing(m1024932.java:4206)
	at main.makeFrame(m1024932.java:9753)
	at main.makeFrame(m1024932.java:9748)
	at main.showFrame(m1024932.java:3705)
	at main.showMaximizedFrame(m1024932.java:4057)
	at main.showDesktop(m1024932.java:371)
	at main.main(m1024932.java:321)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at x30.invokeMethod(x30.java:9075)
	at x30.callOpt_withVarargs(x30.java:14584)
	at x30.callOpt(x30.java:9581)
	at x30.callMain(x30.java:5687)
	at x30.runMainMethod(x30.java:1258)
	at x30.paaRun(x30.java:1234)
	at x30.runProgramQuick(x30.java:1225)
	at x30.runProgram(x30.java:1176)
	at x30.javax2(x30.java:989)
	at x30.javaxmain(x30.java:397)
	at x30.goMain(x30.java:329)
	at x30.main(x30.java:161)
Caused by: com.alee.managers.style.StyleException: Skin 'Light skin' doesn't have any styles for component type: panel[class javax.swing.JPanel, PanelUI, class com.alee.laf.panel.WPanelUI, class com.alee.laf.panel.WebPanelUI, StyleId [ id: 'panel'; parent: null ]]
	at com.alee.managers.style.data.SkinInfo.getStyle(SkinInfo.java:496)
	at com.alee.managers.style.XmlSkin.getStyle(XmlSkin.java:159)
	at com.alee.managers.style.AbstractSkin.applySkin(AbstractSkin.java:64)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:280)
	at com.alee.managers.style.StyleManager.installSkin(StyleManager.java:1055)
	at com.alee.laf.panel.WebPanelUI.installUI(WebPanelUI.java:64)
	at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
	at java.desktop/javax.swing.JPanel.setUI(JPanel.java:150)
	at java.desktop/javax.swing.JPanel.updateUI(JPanel.java:126)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:86)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:109)
	at java.desktop/javax.swing.JPanel.<init>(JPanel.java:117)
	at java.desktop/javax.swing.JRootPane.createGlassPane(JRootPane.java:521)
	at java.desktop/javax.swing.JRootPane.<init>(JRootPane.java:348)
	at java.desktop/javax.swing.JFrame.createRootPane(JFrame.java:279)
	at java.desktop/javax.swing.JFrame.frameInit(JFrame.java:258)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:225)
	at main$194.get(m1024932.java:9756)
	at main$194.get(m1024932.java:1)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at main.invokeMethod(m1024932.java:8386)
	at main.callF(m1024932.java:2499)
	at main$168.run(m1024932.java:8249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
FAIL: java.lang.reflect.InvocationTargetException

```

**Comment by mgarin** [comment]
According to this line from stack trace:
```
Error: ReflectionException: Unable to update field modifiers: public final int com.alee.painter.decoration.shape.Round.topLeft -> 1
```
You're probably running WebLaF on a JDK 12 or newer.

There are some issues with newer JDKs that were shortly explained here: #525

There was already a small patch added that will be available in v1.2.11 update which fixes this problem for Java 12+ with multi-version jar feature usage.

If you want to try it out and see if it fixes WebLaF for you - you can use one of v1.2.11 snapshot versions that can be found here:
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/

Or add it as a Maven project dependency:
```xml
    <dependencies>
        <dependency>
            <groupId>com.weblookandfeel</groupId>
            <artifactId>weblaf-ui</artifactId>
            <version>1.2.11-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>sonatype-snapshot-rep</id>
            <name>Sonatype snapshot repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <layout>default</layout>
            <releases>
                <enabled>true</enabled>
                <updatePolicy>never</updatePolicy>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
```

**Comment by stefan-reich** [comment]
OK, thanks! I will try when I have time.

**Comment by mgarin** [comment]
Update v1.2.11 is now released and will shortly be available in Maven.
You can use it with the next dependency:
```xml
<dependency>
    <groupId>com.weblookandfeel</groupId>
    <artifactId>weblaf-ui</artifactId>
    <version>1.2.11</version>
</dependency>
```
