### ISSUE TITLE
Repeatedly updating components style

### ISSUE THREAD

**Issue by Husker-hub** [mgarin/weblaf#591]
When I apply my style to a ```WebButton```with wrong ```extends```  value I get an exception and the button dissapears - it's ok, but after that, when I apply the style with correct ```extends``` value I also get an exception and ```WebButton``` doesn't appear.

Is there way to return back this ```WebButton```?

Here is my log:

###  Wrong  ```extends``` value
```xml
<skin xmlns="http://weblookandfeel.com/XmlSkin">
    <id>husker.editor.skin</id>
    <class>com.husker.editor.app.skin.CustomSkin</class>
    <supportedSystems>all</supportedSystems>
    <title>Custom skin</title>
    <description>WebLaF Editor Skin</description>
    <author>Husker</author>

   <include nearClass="com.alee.skin.web.WebSkin">resources/skin.xml</include>

    <style type="button" id="preview" extends="ico">
        <painter>
            <decorations>
                <decoration>
                    <WebShape round="0" />
                </decoration>
            </decorations>
        </painter>
    </style>

</skin>

Exception:
com.alee.managers.style.StyleException: Skin 'Custom skin' doesn't have any styles for component type: button[class javax.swing.JButton, ButtonUI, class com.alee.laf.button.WButtonUI, class com.alee.laf.button.WebButtonUI, StyleId [ id: 'button'; parent: null ]]
	at com.alee.managers.style.data.SkinInfo.getStyle(SkinInfo.java:496)
	at com.alee.managers.style.XmlSkin.getStyle(XmlSkin.java:162)
	at com.alee.managers.style.AbstractSkin.removeSkin(AbstractSkin.java:83)
	at com.alee.managers.style.StyleData.removeSkin(StyleData.java:456)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:293)
	at com.alee.managers.style.StyleData.applyCustomSkin(StyleData.java:349)
	at com.alee.managers.style.StyleManager.setSkin(StyleManager.java:1215)
	at com.alee.managers.style.StyleManager.setSkin(StyleManager.java:1199)
	at com.husker.editor.app.skin.CustomSkin.lambda$applySkin$0(CustomSkin.java:52)
	at java.lang.Thread.run(Thread.java:748)
```

###  Correct  ```extends```  value
```xml
<skin xmlns="http://weblookandfeel.com/XmlSkin">
    <id>husker.editor.skin</id>
    <class>com.husker.editor.app.skin.CustomSkin</class>
    <supportedSystems>all</supportedSystems>
    <title>Custom skin</title>
    <description>WebLaF Editor Skin</description>
    <author>Husker</author>

    <include nearClass="com.alee.skin.web.WebSkin">resources/skin.xml</include>

    <style type="button" id="preview" extends="icon">
        <painter>
            <decorations>
                <decoration>
                    <WebShape round="0" />
                </decoration>
            </decorations>
        </painter>
    </style>

</skin>

Exception:
com.alee.managers.style.StyleException: Skin 'Custom skin' doesn't have any styles for component type: button[class javax.swing.JButton, ButtonUI, class com.alee.laf.button.WButtonUI, class com.alee.laf.button.WebButtonUI, StyleId [ id: 'button'; parent: null ]]
	at com.alee.managers.style.data.SkinInfo.getStyle(SkinInfo.java:496)
	at com.alee.managers.style.XmlSkin.getStyle(XmlSkin.java:162)
	at com.alee.managers.style.AbstractSkin.removeSkin(AbstractSkin.java:83)
	at com.alee.managers.style.StyleData.removeSkin(StyleData.java:456)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:293)
	at com.alee.managers.style.StyleData.applyCustomSkin(StyleData.java:349)
	at com.alee.managers.style.StyleManager.setSkin(StyleManager.java:1215)
	at com.alee.managers.style.StyleManager.setSkin(StyleManager.java:1199)
	at com.husker.editor.app.skin.CustomSkin.lambda$applySkin$0(CustomSkin.java:52)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Husker-hub** [comment]
I have found the worst solution - recreate ```Component``` and apply skin again.

**Comment by mgarin** [comment]
This does sound like a weird issue, i'll check this tomorrow and see if I can include a fix in v1.2.11 update.

**Comment by mgarin** [comment]
I found the problem - skin styles compilation happens a bit too late and that causes an issue with the part in `StyleManager` that applies compiled styles to existing components. It basically starts to ignore existing components once skin has changed. I will fix that issue and it shouldn't appear in v1.2.11 anymore.

Code I used for testing this case:
```java
public class StyleEditorTest
{
    public static void main ( final String[] args )
    {
        SwingTest.run ( new Runnable ()
        {
            @Override
            public void run ()
            {
                final WebPanel container = new WebPanel ( new BorderLayout ( 0, 15 ) );
                container.setPadding ( 15 );

                final WebButton button = new WebButton ( StyleId.of ( "preview" ), "Sample button" );
                container.add ( button, BorderLayout.NORTH );

                final WebSyntaxArea editor = new WebSyntaxArea (
                        "<skin xmlns=\"http://weblookandfeel.com/XmlSkin\">\n" +
                                "    <id>husker.editor.skin</id>\n" +
                                "    <class>com.alee.skin.light.WebLightSkin</class>\n" +
                                "    <supportedSystems>all</supportedSystems>\n" +
                                "    <title>Custom skin</title>\n" +
                                "    <description>WebLaF Editor Skin</description>\n" +
                                "    <author>Husker</author>\n" +
                                "\n" +
                                "    <include nearClass=\"com.alee.skin.light.WebLightSkin\">resources/web-light-skin.xml</include>\n" +
                                "\n" +
                                "    <style type=\"button\" id=\"preview\" extends=\"ico\">\n" +
                                "        <painter>\n" +
                                "            <decorations>\n" +
                                "                <decoration>\n" +
                                "                    <WebShape round=\"0\" />\n" +
                                "                </decoration>\n" +
                                "            </decorations>\n" +
                                "        </painter>\n" +
                                "    </style>\n" +
                                "\n" +
                                "</skin>",
                        SyntaxPreset.xml, SyntaxPreset.editable, SyntaxPreset.base, SyntaxPreset.historyLimit
                );
                container.add ( editor, BorderLayout.CENTER );

                new DocumentChangeBehavior<WebSyntaxArea> ( editor )
                {
                    @Override
                    public void documentChanged ( @NotNull final WebSyntaxArea component, @Nullable final DocumentEvent event )
                    {
                        try
                        {
                            final XmlSkin xmlSkin = new XmlSkin ( ( SkinInfo ) XmlUtils.fromXML ( editor.getText () ) );
                            StyleManager.setSkin ( xmlSkin );
                        }
                        catch ( final Exception e )
                        {
                            e.printStackTrace ();
                        }
                    }
                }.install ();

                TestFrame.show ( container );
            }
        } );
    }
}
```

**Comment by mgarin** [comment]
I've added fix for this issue and also an extra fallback for skin installation to ensure that everything else works correctly after new skin installation failed.

**Comment by mgarin** [comment]
This fix will be available in v1.2.11 update which will be released today or tomorrow.

**Comment by Husker-hub** [comment]
I have got the same issue in 1.2.11 after wrong ```extends```:
```xml
<skin xmlns="http://weblookandfeel.com/XmlSkin">
    <id>husker.editor.skin</id>
    <class>com.husker.editor.app.skin.CustomSkin</class>
    <supportedSystems>all</supportedSystems>
    <title>Custom skin</title>
    <description>WebLaF Editor Skin</description>
    <author>Husker</author>
    <include nearClass="com.alee.skin.light.WebLightSkin">resources/web-light-skin.xml</include>

    <style type="button" id="preview" extends="icon" />

</skin>
Exception in thread "AWT-EventQueue-0" com.alee.managers.style.StyleException: Skin 'husker.editor.skin' doesn't have any styles for component type: button[class javax.swing.JButton, ButtonUI, class com.alee.laf.button.WButtonUI, class com.alee.laf.button.WebButtonUI, StyleId [ id: 'button'; parent: null ]]
	at com.alee.managers.style.data.SkinInfo.getStyle(SkinInfo.java:453)
	at com.alee.managers.style.XmlSkin.getStyle(XmlSkin.java:159)
	at com.alee.managers.style.AbstractSkin.removeSkin(AbstractSkin.java:81)
	at com.alee.managers.style.StyleData.removeSkin(StyleData.java:456)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:293)
	at com.alee.managers.style.StyleData.applyCustomSkin(StyleData.java:349)
	at com.alee.managers.style.StyleManager.setSkin(StyleManager.java:1276)
	at com.alee.managers.style.StyleManager.setSkin(StyleManager.java:1260)
	at com.husker.editor.app.skin.CustomSkin.lambda$null$0(CustomSkin.java:57)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```

**Comment by mgarin** [comment]
Do you also get it in my code example from above?

To check it:
1. Launch it and add space at the end of any line -> error will appear for the incorrect skin
2. Fix the extended style from `ico` to `icon` -> style should apply correctly now

**Comment by Husker-hub** [comment]
I use```StyleManager.setSkin(JComponent, XmlSkin)``` inside the new ```Thread``` and it works almost fine except for wrong ```extends``` value. 
If I use ```StyleManager.setSkin(XmlSkin)``` it works fine with ```extends``` everytime, but inside new ```Thread``` my application freezes.

For my application I prefer change skin in new ```Thread```

**Comment by mgarin** [comment]
That is actually pretty bad, I mean changing skin on a separate `Thread` - it has to be done on EDT, just like any other operations with Swing. It is important because when skin is changed it applies itself to all existing components one by one and that involves a lot of work with UI elements. You can *mostly* work with Swing outside of EDT, but the risk is on you - once UI is big enough you're guaranteed to run into issues and weird exceptions. Same with WebLaF and any UI-related managers or features - I can only guarantee they will function correctly when run on EDT.

I have a tool in place with which you can check that you're not running something that should be run on EDT on some other `Thread` - [Forced EDT usage](https://github.com/mgarin/weblaf/wiki/Forced-EDT-usage) - you can enable the checks and see where your application crashes. Those places are recommended to be run on EDT.

**Comment by mgarin** [comment]
Just a note - running stuff on EDT is not really a WebLaF requirement, it is purely dictated by Swing framework. You can check [official note in Swing tutorials](https://docs.oracle.com/javase/tutorial/uiswing/concurrency/dispatch.html) about EDT usage.

Considering that WebLaF generates thousands of events when skin is being replaced - it is highly possible that you will run into issues with it more often than you normally will with Swing when operating outside of EDT.

**Comment by Husker-hub** [comment]
I understand what are you writing about, but that is different issue. I mean you have fixed issue when style applied to every component, not to one.

Here is comparison (after wrong ```extends``` value):

### ```StyleManager.setSkin(JComponent, XmlSkin)``` :
* Inside new ```Thread``` : **Exception!**
```java 
new Thread(() -> {
    SkinInfo skinInfo = XmlUtils.fromXML(text);
    StyleManager.setSkin(component, new XmlSkin(skinInfo));
}).start();
```
* Inside ```EDT``` : **Exception!**
```java 
SwingUtilities.invokeLater(() -> {
    SkinInfo skinInfo = XmlUtils.fromXML(text);
    StyleManager.setSkin(component, new XmlSkin(skinInfo));
});
```

### ```StyleManager.setSkin(XmlSkin)``` 
* Inside new ```Thread``` : **Freeze** (OK)
* Inside ```EDT``` : **OK**

Applying skin to one of the components is still strange.

**Comment by mgarin** [comment]
Ok, that makes sense, it's been a while since I actually applied skin to a particular component so I totally missed it in your comment. Thanks for pointing it out :)

I'll try it and see if I can reproduce & fix the problem quickly.

**Comment by mgarin** [comment]
I found the source of problem, but it's quite a tricky thing, I'll need some time to figure out how to change it to fix the per-component skin usage (there are actually a few different problems, but in case of editor you're only seeing one of them).

As a temporary solution - you can call `install ()` on your loaded skin before applying it:
```java
final XmlSkin xmlSkin = new XmlSkin ( ( SkinInfo ) XmlUtils.fromXML ( text ) );
xmlSkin.install ();
StyleManager.setSkin ( component, xmlSkin );
```
This will ensure that corrupted skins do not break component information stored internally in `StyleManager`.

**Comment by mgarin** [comment]
This bug actually revealed a few big flaws with the current implementation of the styles loading and usage. The good thing is - I was planning to change behavior overall anyway for the next update, so I will be working on that for quite some time, but as a result it should fix these issues and also improve initialization performance, so loading skin from the XML will be extremely fast.

**Comment by mgarin** [comment]
Moving this to v1.2.12, not yet sure if fix will be implemented earlier or at the same time as the performance improvements for skin initialization.
