### ISSUE TITLE
Rendering fonts under Apple M1 

### ISSUE THREAD

**Issue by mokun** [mgarin/weblaf#665]
Recently I've switched to using my new Apple mac mini with M1 CPU.

I have no problems running the core program. 

However, as soon as I start the Swing windows which currently depends on Weblaf, 

It could be just a font initialization error. It points to calling WebLookAndFeel.install() when it happens in my initializeWeblaf() in MainWindow.java

```
[pool-1-thread-1] ERROR com.alee.laf.NativeFonts - Unable to retrieve native Mac OS X font using method: com.apple.laf.AquaFonts.getControlTextFont()
java.lang.reflect.InaccessibleObjectException: Unable to make public static javax.swing.plaf.FontUIResource com.apple.laf.AquaFonts.getControlTextFont() accessible: module java.desktop does not "exports com.apple.laf" to unnamed module @7113b13f
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.alee.utils.ReflectUtils.getMethodImpl(ReflectUtils.java:1913)
	at com.alee.utils.ReflectUtils.getMethodImpl(ReflectUtils.java:1873)
	at com.alee.utils.ReflectUtils.getMethod(ReflectUtils.java:1842)
	at com.alee.utils.ReflectUtils.callStaticMethod(ReflectUtils.java:1467)
	at com.alee.utils.ReflectUtils.callStaticMethod(ReflectUtils.java:1421)
	at com.alee.laf.NativeFonts.getMacOSFont(NativeFonts.java:664)
	at com.alee.laf.NativeFonts.get(NativeFonts.java:271)
	at com.alee.laf.WebLookAndFeel.<clinit>(WebLookAndFeel.java:243)
	at org.mars_sim.msp.ui.swing.MainWindow.initializeWeblaf(MainWindow.java:1189)
```

Can you think of any possible workarounds for this situation with M1 ?

Thanks !

**Comment by mgarin** [comment]
This seems like an issue with newer Java version. You might have to add some extra JVM options to avoid it, I've mentioned it in the wiki article here: https://github.com/mgarin/weblaf/wiki/Java-9-and-higher

WebLaF is simply not able to access a proprietary method, problem should go away if you add this JVM option:
```
--add-opens java.desktop/com.apple.laf=ALL-UNNAMED
```
There is unfortunately no way to workaround it right now - WebLaF has to use reflection to access multiple proprietary classes and methods to properly configure fonts, antialiasing and some other component settings.

I'm not sure if you've used any of these JVM options before and how it is related to switching to M1. My guess is - you simply have a newer JVM version (>=12) on your M1 that caused this issue to appear. On earlier JVM versions (<=11) reflection was not forcefully limited by default.

**Comment by mokun** [comment]
> I'm not sure if you've used any of these JVM options before and how it is related to switching to M1. My guess is - you simply have a newer JVM version (>=12) on your M1 that caused this issue to appear. On earlier JVM versions (<=11) reflection was not forcefully limited by default.

Yes I just found out it that if I switch to using Java 11, instead of Java 15, the font problem in intelliJ for M1 goes away.

**Comment by mgarin** [comment]
But are you able to avoid the problem with the JVM options?
