### ISSUE TITLE
WebLaF not working with jdk-16

### ISSUE THREAD

**Issue by Abu-Abdullah** [mgarin/weblaf#667]
Hi @mgarin 
I just tried the 1.2.13 with jdk-16 and got this error:
```
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.thoughtworks.xstream.XStream.setupConverters(XStream.java:832)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:574)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:496)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:465)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:411)
	at com.thoughtworks.xstream.XStream.<init>(XStream.java:392)
	at com.alee.utils.XmlUtils.initializeXStream(XmlUtils.java:128)
	at com.alee.utils.XmlUtils.getXStream(XmlUtils.java:106)
	at com.alee.managers.UIManagers.initialize(UIManagers.java:65)
	at com.alee.laf.WebLookAndFeel.initializeManagers(WebLookAndFeel.java:1077)
	at com.alee.laf.WebLookAndFeel.initialize(WebLookAndFeel.java:397)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:591)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:638)
	at com.alee.utils.LafUtils.setupLookAndFeel(LafUtils.java:206)
	at com.alee.utils.LafUtils.setupLookAndFeel(LafUtils.java:193)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:1120)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:1099)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:1087)
```

trying to find the reason, it seems it is about the old xstream version, the solution is to update it to 1.4.16

**Comment by mgarin** [comment]
It could be. I'll see if I can bump XStream without causing any issues. Previously I've had some problems with newer versions because of some internal changes they've done that affected deserialization, so I'll need to be careful with that.

**Comment by Sciss** [comment]
Hi there, checking on this. JDK 17 seems baseline now (e.g. Debian's new default). How difficult would it be to switch to a newer XStream version that doesn't have this problem?

**Comment by Sciss** [comment]
I managed to make it work with some small changes and additional vm arguments: https://github.com/Sciss/weblaf_temp/pull/1

(I don't know how to make this a pull request, because I have already a different fork of the project on GH)

**Comment by Sciss** [comment]
Moved off GitHub. Corresponding work: https://codeberg.org/sciss/weblaf_temp/pulls/1
