### ISSUE TITLE
exception on jdk21

### ISSUE THREAD

**Issue by lcy-1024** [mgarin/weblaf#716]
**Description**

ENV:
<dependency>
    <groupId>com.weblookandfeel</groupId>
    <artifactId>weblaf-ui</artifactId>
    <version>1.2.14</version>
</dependency>
graalvm-jdk-21.0.3+7.1

-------------------------
D:\work\java\graalvm-jdk-21.0.3+7.1\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.desktop/javax.swing=ALL-UNNAMED --add-opens java.desktop/javax.swing.text=ALL-UNNAMED --add-opens java.desktop/java.awt.font=ALL-UNNAMED --add-opens java.desktop/java.awt.geom=ALL-UNNAMED --add-opens java.desktop/java.awt=ALL-UNNAMED --add-opens java.desktop/java.beans=ALL-UNNAMED --add-opens java.desktop/javax.swing.table=ALL-UNNAMED --add-opens java.desktop/com.sun.awt=ALL-UNNAMED --add-opens java.desktop/sun.awt=ALL-UNNAMED --add-opens java.desktop/sun.swing=ALL-UNNAMED --add-opens java.desktop/sun.font=ALL-UNNAMED --add-opens java.desktop/javax.swing.plaf.basic=ALL-UNNAMED --add-opens java.desktop/javax.swing.plaf.synth=ALL-UNNAMED --add-opens java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED --add-opens java.desktop/com.sun.java.swing.plaf.gtk=ALL-UNNAMED --add-opens java.desktop/com.apple.laf=ALL-UNNAMED -XX:TieredStopAtLevel=1 -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true "-Dmanagement.endpoints.jmx.exposure.include=*" "-javaagent:D:\work\JetBrains\IntelliJ IDEA 2024.1.4\lib\idea_rt.jar=8151:D:\work\JetBrains\IntelliJ IDEA 2024.1.4\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath ....

WARNING: package com.sun.java.swing.plaf.gtk not in java.desktop
WARNING: package com.apple.laf not in java.desktop
WARNING: package com.sun.awt not in java.desktop

Constructor threw exception; nested exception is java.lang.RuntimeException: Unable to initialize LaF for class name: com.alee.laf.WebLookAndFeel

Caused by: java.lang.RuntimeException: Unable to initialize LaF for class name: com.alee.laf.WebLookAndFeel
	at com.alee.utils.LafUtils.setupLookAndFeel(LafUtils.java:210)
	at com.alee.utils.LafUtils.setupLookAndFeel(LafUtils.java:193)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:1146)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:1125)
	at com.alee.laf.WebLookAndFeel.install(WebLookAndFeel.java:1113)

Caused by: com.alee.utils.reflection.ReflectionException: Unable to instantiate skin for class: class com.alee.skin.light.WebLightSkin
	at com.alee.utils.reflection.LazyInstance.create(LazyInstance.java:79)
	at com.alee.managers.style.StyleManager.setSkin(StyleManager.java:1003)
	at com.alee.managers.style.StyleManager.initialize(StyleManager.java:271)
	at com.alee.laf.WebLookAndFeel.initializeManagers(WebLookAndFeel.java:1099)
	at com.alee.laf.WebLookAndFeel.initialize(WebLookAndFeel.java:407)

Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.alee.utils.ReflectUtils.createInstance(ReflectUtils.java:1285)
	at com.alee.utils.reflection.LazyInstance.create(LazyInstance.java:74)
	... 33 common frames omitted
Caused by: com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.alee.managers.style.StyleException
cause-message       : Unable to load icon set 'class com.alee.iconset.LightIconSet'
class               : com.alee.managers.style.data.SkinInfo
required-type       : com.alee.managers.style.data.SkinInfo
converter-type      : com.alee.managers.style.data.SkinInfoConverter
path                : /skin/iconSet
line number         : 15
version             : 1.4.12
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:77)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1487)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1467)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1347)
	at com.alee.utils.XmlUtils.fromXML(XmlUtils.java:416)
	at com.alee.utils.XmlUtils.fromXML(XmlUtils.java:378)
	at com.alee.managers.style.XmlSkin.<init>(XmlSkin.java:58)
	at com.alee.skin.light.WebLightSkin.<init>(WebLightSkin.java:35)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 37 common frames omitted
Caused by: com.alee.managers.style.StyleException: Unable to load icon set 'class com.alee.iconset.LightIconSet'
	at com.alee.managers.style.data.SkinInfoConverter.readIconSet(SkinInfoConverter.java:360)
	at com.alee.managers.style.data.SkinInfoConverter.unmarshal(SkinInfoConverter.java:211)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 50 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.alee.utils.ReflectUtils.createInstance(ReflectUtils.java:1285)
	at com.alee.managers.style.data.SkinInfoConverter.readIconSet(SkinInfoConverter.java:355)
	... 52 common frames omitted
Caused by: com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.alee.managers.icon.IconException
cause-message       : Unable to load XmlIconSet
class               : com.alee.managers.icon.set.XmlIconSet
required-type       : com.alee.managers.icon.set.XmlIconSet
converter-type      : com.alee.managers.icon.set.XmlIconSetConverter
path                : /IconSet
line number         : 1
version             : 1.4.12
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:77)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1487)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1467)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1446)
	at com.alee.utils.XmlUtils.fromXML(XmlUtils.java:429)
	at com.alee.utils.XmlUtils.fromXML(XmlUtils.java:391)
	at com.alee.managers.icon.set.XmlIconSet.<init>(XmlIconSet.java:48)
	at com.alee.iconset.LightIconSet.<init>(LightIconSet.java:35)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	... 56 common frames omitted
Caused by: com.alee.managers.icon.IconException: Unable to load XmlIconSet
	at com.alee.managers.icon.set.XmlIconSetConverter.unmarshal(XmlIconSetConverter.java:98)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 69 common frames omitted
Caused by: java.lang.UnsupportedOperationException: null
	at java.base/java.lang.invoke.VarForm.getMemberName(VarForm.java:118)
	at com.alee.utils.reflection.FieldHelper.setFieldModifiers(FieldHelper.java:39)
	at com.alee.utils.ReflectUtils.setFieldValue(ReflectUtils.java:960)
	at com.alee.utils.ReflectUtils.setFieldValue(ReflectUtils.java:860)
	at com.alee.managers.icon.set.XmlIconSetConverter.unmarshal(XmlIconSetConverter.java:69)
	... 70 common frames omitted

**Comment by Luka9kw** [comment]
I'm having the same issue
